# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_genadmin', '0002_auto_20161206_1859'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_user', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('key', models.CharField(db_index=True, max_length=12)),
                ('slug', models.SlugField(max_length=32)),
                ('contact', models.CharField(max_length=13)),
                ('address_line_1', models.TextField(blank=True, verbose_name='Address Line 1')),
                ('address_line_2', models.TextField(blank=True, verbose_name='Address Line 2')),
                ('state', models.CharField(blank=True, max_length=30)),
                ('pincode', models.PositiveIntegerField(blank=True)),
                ('subject', models.ManyToManyField(to='school_genadmin.Subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_student_user_tenant', to='school_user.Tenant')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_student_user_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.TextField()),
                ('institute', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('reward', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentEducation_student', to='school_student.Student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentEducation_student_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='student_guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.TextField()),
                ('name', models.TextField()),
                ('contact', models.CharField(max_length=13)),
                ('address', models.TextField(blank=True)),
                ('qualification', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentGuardian_student', to='school_student.Student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentGuardian_student_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('key', 'tenant')]),
        ),
    ]
