# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 00:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0003_auto_20161208_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_guardian',
            name='name',
        ),
        migrations.AddField(
            model_name='student_guardian',
            name='first_name',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_guardian',
            name='last_name',
            field=models.CharField(default='g', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='address_line_1',
            field=models.TextField(blank=True, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_line_2',
            field=models.TextField(blank=True, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='local_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Please fill this if you have some other student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_student_user_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_education',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_education',
            name='reward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_guardian',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_guardian',
            name='profession',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_guardian',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_guardian',
            name='relation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student_guardian',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentGuardian_student_user_tenant', to='school_user.Tenant'),
        ),
    ]
