# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0005_auto_20161209_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default='1900-01-01', verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
