# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0008_auto_20161221_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A Positive'), ('B+', 'B Positive'), ('O+', 'O Positive'), ('AB+', 'AB Positive'), ('A-', 'A Negative'), ('B-', 'B Negative'), ('O-', 'O Negative'), ('AB-', 'AB Negative'), ('O', 'Other')], max_length=3, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
