# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0009_auto_20170104_1443'),
        ('school_student', '0009_auto_20170104_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_student_genadmin_batch', to='school_genadmin.Batch'),
            preserve_default=False,
        ),
    ]
