# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0010_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2'),
        ),
    ]
