# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0012_auto_20170120_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
