# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-09 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0015_auto_20170124_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_student_genadmin_batch', to='school_genadmin.Batch'),
            preserve_default=False,
        ),
    ]
