# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0017_auto_20170219_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A Positive'), ('B+', 'B Positive'), ('O+', 'O Positive'), ('AB+', 'AB Positive'), ('A-', 'A Negative'), ('B-', 'B Negative'), ('O-', 'O Negative'), ('AB-', 'AB Negative'), ('Ot', 'Other')], max_length=3, null=True, verbose_name='Blood Group'),
        ),
    ]
