# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0019_auto_20170308_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
