# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 03:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_user', '0004_auto_20161217_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('account_type', models.CharField(choices=[('Current Assets', 'Current Assets'), ('Long Term Assets', 'Long Term Assets'), ('Current Liabilities', 'Current Liabilities'), ('Long Term Liabilities', 'Long Term Liabilities'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Indirect Revenue', 'Indirect Revenue'), ('Direct Expense', 'Indirect Expense'), ('Direct Expense', 'Indirect Expense'), ('Equity', 'Equity')], max_length=12, verbose_name='Account type')),
                ('slug', models.SlugField()),
                ('key', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='accounting_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True)),
                ('end', models.DateField(db_index=True)),
                ('current_period', models.BooleanField(verbose_name='Current Accounting Period?')),
                ('slug', models.SlugField(max_length=45)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountingPeriod_account_user_tenant', to='school_user.Tenant')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('journal_type', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=20)),
                ('key', models.CharField(db_index=True, max_length=20)),
                ('local_key', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Unique local voucher number, can be left blank.')),
            ],
            options={
                'ordering': ('date', 'group'),
            },
        ),
        migrations.CreateModel(
            name='journal_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=6, verbose_name='Transaction type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntry_account', to='school_account.Account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntry_journal', to='school_account.Journal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntry_account_user_tenant', to='school_user.Tenant')),
            ],
            options={
                'ordering': ('journal', '-transaction_type'),
            },
        ),
        migrations.CreateModel(
            name='journal_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalGroup_account_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ledger_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=41)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgergroup_account_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='payment_mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Payment Mode Name')),
                ('default', models.BooleanField(default=False, verbose_name='Default Payment Mode ?')),
                ('slug', models.SlugField(max_length=32)),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentMode_account', to='school_account.Account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentMode_account_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_journalGroup', to='school_account.journal_group'),
        ),
        migrations.AddField(
            model_name='journal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_account_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AddField(
            model_name='account',
            name='ledger_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_ledgerGroup', to='school_account.ledger_group'),
        ),
        migrations.AddField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_account_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='payment_mode',
            unique_together=set([('payment_account', 'name', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='ledger_group',
            unique_together=set([('name', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='journal_group',
            unique_together=set([('name', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='journal_entry',
            unique_together=set([('journal', 'account')]),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set([('key', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='accounting_period',
            unique_together=set([('start', 'end', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('key', 'tenant')]),
        ),
    ]
