# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-30 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('name', 'tenant'), ('key', 'tenant')]),
        ),
    ]
