# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0004_auto_20170104_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
