# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 06:09
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0005_account_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='local_key',
        ),
        migrations.RemoveField(
            model_name='journal_entry',
            name='remarks',
        ),
        migrations.AddField(
            model_name='journal',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal_entry',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
