# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0006_auto_20170106_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='remark',
            new_name='remarks',
        ),
    ]
