# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0008_remove_journal_journal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='value',
            new_name='current_credit',
        ),
        migrations.AddField(
            model_name='account',
            name='current_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
