# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0011_auto_20170106_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='opening_credit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='opening_debit',
        ),
    ]
