# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-10 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0013_auto_20170106_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting_period',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
