# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-01 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0015_auto_20170120_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_type', 'name']},
        ),
    ]
