# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0016_auto_20170201_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting_period',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='journal_group',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ledger_group',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='payment_mode',
            name='slug',
        ),
        migrations.AlterField(
            model_name='account',
            name='key',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='journal',
            name='remarks',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(),
        ),
    ]
