# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0018_auto_20170219_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sub_account_type',
            field=models.CharField(blank=True, choices=[('PFEEL', 'PF Employee - Liability'), ('PFERL', 'PF Employer - Liability'), ('PFERE', 'PF Employer - Expense'), ('ESEEL', 'ESI Employee - Liability'), ('ESERL', 'ESI Employer - Liability'), ('ESERE', 'ESI Employer - Expense')], max_length=5, null=True, verbose_name='Sub Account type'),
        ),
    ]
