# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0019_account_sub_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
