# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0020_auto_20170223_2009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journal_entry',
            unique_together=set([]),
        ),
    ]
