# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0021_auto_20170310_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_account_type',
            field=models.CharField(blank=True, choices=[('PFEEL', 'PF Employee - Liability'), ('PFERL', 'PF Employer - Liability'), ('PSERL', 'EPS Employer - Liability'), ('PFADL', 'PF Admin Charges - Liability'), ('ESRE', 'Employer Statutory - Expense'), ('ESEEL', 'ESI Employee - Liability'), ('ESERL', 'ESI Employer - Liability'), ('EDLIL', 'EDLI Employer - Liability'), ('EDACL', 'EDLI Admin Charges - Liability')], max_length=5, null=True, verbose_name='Sub Account type'),
        ),
    ]
