# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 01:42
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0022_auto_20170311_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_entry',
            name='this_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='this_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
    ]
