# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0023_auto_20170313_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal_entry',
            name='this_credit',
        ),
        migrations.RemoveField(
            model_name='journal_entry',
            name='this_debit',
        ),
    ]
