# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0024_auto_20170313_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_year',
            name='current_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account_year',
            name='current_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
