# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0002_auto_20161209_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_teacher_user_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
