# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-18 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0003_auto_20161209_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_teacher_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
