# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0004_teacher_school_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school_teacher_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
