# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0007_auto_20161227_0744'),
        ('school_teacher', '0006_auto_20170104_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_group',
            field=models.ManyToManyField(to='school_genadmin.class_group'),
        ),
    ]
