# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-04 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0009_teacher_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_group',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school_teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
