# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0011_teacher_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='staff_type',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Principal', 'Principal'), ('Accounts', 'Accounts'), ('Collector', 'Fee Collector')], max_length=12),
        ),
    ]
