# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0013_auto_20170219_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(default='2016-01-01'),
            preserve_default=False,
        ),
    ]
