# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0015_auto_20170316_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='staff_type',
            field=models.CharField(choices=[('Master', 'Master'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Principal', 'Principal'), ('Accounts', 'Accounts'), ('Collector', 'Fee Collector')], max_length=12),
        ),
    ]
