# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 04:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0005_auto_20170101_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 10, 19, 49, 102309)),
        ),
         migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Master', 'Master'), ('Account', 'Account'), ('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=10),
        ),
    ]
