# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0006_auto_20170104_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered_on',
        ),
    ]
