# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0006_auto_20170104_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered_on',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 17, 29, 35, 2196)),
        ),
    ]
