# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 05:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0008_auto_20170123_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 23, 11, 15, 7, 390680)),
        ),
    ]
