# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-12 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0010_auto_20170212_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='trial_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 13, 0, 31, 32, 842807)),
        ),
    ]
