# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 04:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0011_auto_20170213_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Master', 'Master'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Principal', 'Principal'), ('Account', 'Account'), ('Collector', 'Fee Collector'), ('Student', 'Student'), ('Parent', 'Parent')], max_length=10),
        ),
    ]
