# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 03:28
from __future__ import unicode_literals

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0012_auto_20170215_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='board',
            field=models.TextField(blank=True, null=True, verbose_name='Affiliated Board'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Affiliation Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
