# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0013_auto_20170218_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='registered_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 19, 16, 15, 14, 513645)),
        ),
    ]
