# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0015_auto_20170219_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='registered_on',
            field=models.DateTimeField(),
        ),
    ]
