# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0016_auto_20170310_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='no_of_profile',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
