# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-30 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0002_auto_20161230_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearly_fee_list',
            name='month',
        ),
        migrations.AddField(
            model_name='yearly_fee',
            name='month',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
