# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-30 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0003_auto_20161230_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearly_fee',
            name='name',
            field=models.TextField(),
        ),
    ]
