# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0004_auto_20161230_1025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group_default_fee',
            unique_together=set([('classgroup', 'year', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='student_fee',
            unique_together=set([('student', 'year', 'tenant')]),
        ),
    ]
