# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0015_auto_20170124_1002'),
        ('school_fees', '0005_auto_20170106_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_fee_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=3)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('paid_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('slug', models.SlugField(max_length=56)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentFeePayment_fees_student_student', to='school_student.Student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentFeePayment_fees_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterField(
            model_name='yearly_fee',
            name='month',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='student_fee_payment',
            unique_together=set([('student', 'year', 'tenant')]),
        ),
    ]
