# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0029_auto_20170227_0102'),
        ('school_fees', '0008_auto_20170219_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_fee_payment',
            name='student_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studentFeePayment_fees_eduadmin_classSection', to='school_eduadmin.class_section'),
            preserve_default=False,
        ),
    ]
