# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0009_student_fee_payment_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_fee',
            name='total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
