# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0010_student_fee_total_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_fee',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='student_fee',
            name='total_fee',
        ),
        migrations.RemoveField(
            model_name='yearly_fee',
            name='slug',
        ),
        migrations.AddField(
            model_name='monthly_fee',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='yearly_fee',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
