# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0012_remove_group_default_fee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_fee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='yearly_fee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='monthly_fee_list',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='yearly_fee_list',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
