# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0017_tenant_no_of_profile'),
        ('school_fees', '0013_auto_20170316_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_line_item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_fee_payment',
            name='slug',
        ),
        migrations.AddField(
            model_name='payment_line_item',
            name='fee_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentLineItem_studentFeePayment', to='school_fees.student_fee_payment'),
        ),
        migrations.AddField(
            model_name='payment_line_item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentLineItem_fees_user_tenant', to='school_user.Tenant'),
        ),
    ]
