# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0014_auto_20170317_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_default_fee',
            name='monthly_fee',
        ),
        migrations.AddField(
            model_name='group_default_fee',
            name='monthly_fee',
            field=models.ManyToManyField(db_index=True, related_name='groupDefaultFee_monthlyFee', to='school_fees.monthly_fee'),
        ),
        migrations.RemoveField(
            model_name='student_fee',
            name='monthly_fee',
        ),
        migrations.AddField(
            model_name='student_fee',
            name='monthly_fee',
            field=models.ManyToManyField(db_index=True, related_name='studentFee_monthlyFee', to='school_fees.monthly_fee'),
        ),
    ]
