# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 03:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0017_tenant_no_of_profile'),
        ('school_account', '0024_auto_20170313_0925'),
        ('school_fees', '0015_auto_20170321_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='generic_fee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('month', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=None)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genericFee_fees_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='generic_fee_list',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geericFeeList_fees_account_account', to='school_account.Account')),
                ('generic_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geenricFeeList_yearlyFee', to='school_fees.generic_fee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genericFeeList_fees_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterField(
            model_name='yearly_fee_list',
            name='yearly_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearlyFeeList_yearlyFee', to='school_fees.yearly_fee'),
        ),
        migrations.AlterUniqueTogether(
            name='generic_fee_list',
            unique_together=set([('generic_fee', 'account')]),
        ),
        migrations.AlterUniqueTogether(
            name='generic_fee',
            unique_together=set([('name', 'tenant')]),
        ),
    ]
