# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0016_auto_20170322_0848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthly_fee',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='monthly_fee',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='monthly_fee_list',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='monthly_fee_list',
            name='account',
        ),
        migrations.RemoveField(
            model_name='monthly_fee_list',
            name='monthly_fee',
        ),
        migrations.RemoveField(
            model_name='monthly_fee_list',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='yearly_fee',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='yearly_fee',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='yearly_fee_list',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='yearly_fee_list',
            name='account',
        ),
        migrations.RemoveField(
            model_name='yearly_fee_list',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='yearly_fee_list',
            name='yearly_fee',
        ),
        migrations.RemoveField(
            model_name='group_default_fee',
            name='monthly_fee',
        ),
        migrations.RemoveField(
            model_name='group_default_fee',
            name='yearly_fee',
        ),
        migrations.RemoveField(
            model_name='student_fee',
            name='monthly_fee',
        ),
        migrations.RemoveField(
            model_name='student_fee',
            name='yearly_fee',
        ),
        migrations.AddField(
            model_name='group_default_fee',
            name='generic_fee',
            field=models.ManyToManyField(db_index=True, related_name='groupDefaultFee_genericFee', to='school_fees.generic_fee'),
        ),
        migrations.AddField(
            model_name='student_fee',
            name='generic_fee',
            field=models.ManyToManyField(db_index=True, related_name='studentFee_genericFee', to='school_fees.generic_fee'),
        ),
        migrations.DeleteModel(
            name='monthly_fee',
        ),
        migrations.DeleteModel(
            name='monthly_fee_list',
        ),
        migrations.DeleteModel(
            name='yearly_fee',
        ),
        migrations.DeleteModel(
            name='yearly_fee_list',
        ),
    ]
