# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0017_auto_20170322_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_fee',
            name='slug',
        ),
    ]
