# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees', '0018_remove_student_fee_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generic_fee_list',
            unique_together=set([]),
        ),
    ]
