# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0017_tenant_no_of_profile'),
        ('school_fees', '0019_auto_20170328_0816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generic_fee',
            unique_together=set([('name', 'is_active', 'tenant')]),
        ),
    ]
