# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0017_tenant_no_of_profile'),
        ('school_student', '0021_auto_20170316_1139'),
        ('school_fees', '0020_auto_20170412_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_late_fee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('name', models.CharField(default='Late Fee', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentLateFee_fees_student_student', to='school_student.Student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentLateFee_fees_user_tenant', to='school_user.Tenant')),
            ],
        ),
    ]
