# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0025_auto_20170325_0908'),
        ('school_user', '0017_tenant_no_of_profile'),
        ('school_fees', '0021_student_late_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='late_fee_calculation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_payment_date', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('name', models.CharField(default='Late Fee', max_length=80)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateFeeCalculation_fees_account_account', to='school_account.Account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateFeeCalculation_fees_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='late_fee_slab',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('days_after_due', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('last_slab', models.BooleanField(db_index=True, default=False)),
                ('late_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateFeeSlab_lateFeeCalculation', to='school_fees.late_fee_calculation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateFeeSlab_fees_user_tenant', to='school_user.Tenant')),
            ],
        ),
    ]
