# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0048_auto_20170419_2114'),
        ('school_fees', '0022_late_fee_calculation_late_fee_slab'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_late_fee',
            name='paid_on',
            field=models.DateField(default='2016-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_late_fee',
            name='student_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='studentLateFee_fees_eduadmin_classSection', to='school_eduadmin.class_section'),
            preserve_default=False,
        ),
    ]
