# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=12)),
                ('slug', models.SlugField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='purchaseLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_key', models.CharField(max_length=20)),
                ('subproduct_key', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('free', models.PositiveSmallIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_type', models.CharField(max_length=15)),
                ('vat_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseLineItem_purchaseInvoice', to='distribution_purchase.purchaseInvoice')),
            ],
        ),
    ]
