# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution_purchase', '0001_initial'),
        ('distribution_user', '0001_initial'),
        ('distribution_master', '0002_auto_20160904_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_purchase_user_tenant', to='distribution_user.Tenant'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='vendor_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseInvoice_purchase_master_vendor', to='distribution_master.Vendor'),
        ),
    ]
