# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0013_auto_20161001_0720'),
        ('distribution_purchase', '0002_auto_20160904_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseInvoice_purchase_master_warehouse', to='distribution_master.Warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseInvoice_purchase_user_tenant', to='distribution_user.Tenant'),
        ),
    ]
