# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_user', '0001_initial'),
        ('distribution_master', '0015_auto_20161014_1119'),
        ('distribution_purchase', '0004_purchasepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='debitNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(blank=True, max_length=12)),
                ('note_type', models.CharField(choices=[('Goods Return', 'Goods Return'), ('Payment Adjustment', 'Payment Adjustment')], max_length=12)),
                ('slug', models.SlugField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('invoice_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debitNote_purchaseInvoice', to='distribution_purchase.purchaseInvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitNote_purchase_user_tenant', to='distribution_user.Tenant')),
                ('vendor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitNote_purchase_master_vendor', to='distribution_master.Vendor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitNote_purchase_master_warehouse', to='distribution_master.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='debitNoteLineDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('debitnote_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitNoteLineDetails_debitNote', to='distribution_purchase.debitNote')),
            ],
        ),
        migrations.CreateModel(
            name='debitNoteLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_key', models.CharField(max_length=20)),
                ('subproduct_key', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('debitnote_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitNoteLineItem_debitNote', to='distribution_purchase.debitNote')),
            ],
        ),
    ]
