# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_purchase', '0007_auto_20161023_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnotelineitem',
            name='inventory_type',
            field=models.CharField(choices=[('Reusable', 'Reusable'), ('Returnable', 'Returnable')], default='Reusable', max_length=12),
            preserve_default=False,
        ),
    ]
