# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_purchase', '0008_debitnotelineitem_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnotelineitem',
            name='vat_type',
            field=models.CharField(default='No VAT', max_length=30),
            preserve_default=False,
        ),
    ]
