# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 05:20
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor_master', '0013_auto_20170618_1050'),
        ('distributor_user', '0007_auto_20170616_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_line_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('unit_multi', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('discount_type', models.PositiveSmallIntegerField(default=0)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cgst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sgst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('igst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('line_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiceLineItem_retailSales_master_product', to='distributor_master.Product')),
            ],
        ),
        migrations.CreateModel(
            name='retail_invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.PositiveIntegerField(db_index=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('customer_name', models.CharField(db_index=True, max_length=200)),
                ('customer_address', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone_no', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_gender', models.CharField(max_length=1)),
                ('customer_dob', models.DateField(blank=True, null=True)),
                ('warehouse_address', models.TextField()),
                ('warehouse_state', models.CharField(max_length=4)),
                ('warehouse_city', models.CharField(max_length=50)),
                ('warehouse_pin', models.CharField(max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailInvoice_retailsales_master_retailCustomer', to='distributor_master.retail_customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailInvoice_sales_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailInvoice_retailsales_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='retail_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceLineItem_retailInvoice', to='retail_sales.retail_invoice'),
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceLineItem_retailSales_user_tenant', to='distributor_user.Tenant'),
        ),
    ]
