# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0002_auto_20170618_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_line_item',
            old_name='line_tax',
            new_name='line_before_tax',
        ),
    ]
