# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0003_auto_20170618_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_line_item',
            old_name='discount_value',
            new_name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice_line_item',
            name='discount_type',
        ),
    ]
