# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0004_auto_20170620_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_invoice',
            name='cgsttotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='retail_invoice',
            name='sgsttotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
