# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 08:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0005_auto_20170620_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_line_item',
            name='other_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
