# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0006_auto_20170704_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_line_item',
            name='product_hsn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
