# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0008_invoice_line_item_quantity_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_line_item',
            name='is_tax_included',
            field=models.BooleanField(default=False),
        ),
    ]
