# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0012_auto_20170710_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_invoice',
            name='payment_mode_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='retail_invoice',
            name='payment_mode_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
