# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0014_auto_20170915_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_invoice',
            name='roundoff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
