# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-18 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0015_retail_invoice_roundoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_line_item',
            name='unit_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
