# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-11 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0016_invoice_line_item_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retail_invoice',
            name='invoice_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
