# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0017_auto_20171211_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_invoice',
            name='total_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
