# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0018_retail_invoice_total_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_line_item',
            name='unit_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
