# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_sales', '0019_return_line_item_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_return',
            name='return_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
