# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_teacher', '0013_auto_20170219_1615'),
        ('school_account', '0020_auto_20170223_2009'),
        ('school_hr', '0006_auto_20170220_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_salary_structure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('working_days', models.PositiveSmallIntegerField(verbose_name='Number of working days in month')),
                ('salary_cycle_start', models.PositiveSmallIntegerField()),
                ('salary_cycle_end', models.PositiveSmallIntegerField()),
                ('salary_cycle_payment', models.PositiveSmallIntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicSalaryStructure_salary_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='cadre_default_salary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('slug', models.SlugField()),
                ('cadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadreDefaultSalary_salary_hr_staffCadre', to='school_hr.staff_cadre')),
            ],
        ),
        migrations.CreateModel(
            name='epf_eps_employer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('rule', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Statutory rule')),
                ('is_active', models.BooleanField(default=True)),
                ('epf_ceiling', models.PositiveIntegerField(blank=True, null=True)),
                ('epf_predefined', models.PositiveIntegerField(blank=True, null=True)),
                ('epf_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eps_ceiling', models.PositiveIntegerField(blank=True, null=True)),
                ('eps_predefined', models.PositiveIntegerField(blank=True, null=True)),
                ('eps_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calculate_epf_admin', models.BooleanField(default=False)),
                ('epf_admin_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('epf_admin_minimun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('epf_admin_predefined', models.PositiveIntegerField(blank=True, null=True)),
                ('epf_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epfEmployer_salary_account_account', to='school_account.Account')),
                ('epf_admin_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epfAdmin_salary_account_account', to='school_account.Account')),
                ('eps_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epsEmployer_salary_account_account', to='school_account.Account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epfEpsEmployer_salary_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='esi_employer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('rule', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Statutory rule')),
                ('is_active', models.BooleanField(default=True)),
                ('ceiling', models.PositiveIntegerField(blank=True, null=True)),
                ('predefined', models.PositiveIntegerField(blank=True, null=True)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('esi_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esiEmployer_salary_account_account', to='school_account.Account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esiEmployer_salary_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='monthly_salary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlySalary_salary_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='monthly_salary_list',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_payslip', models.BooleanField(default=True)),
                ('serial_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('affect_pf', models.BooleanField(default=False)),
                ('affect_esi', models.BooleanField(default=False)),
                ('affect_gratuity', models.BooleanField(default=False)),
                ('affect_lop', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlySalaryList_salary_account_account', to='school_account.Account')),
                ('monthly_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlySalaryList_monthlySalary', to='school_salary.monthly_salary')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlySalaryList_salary_user_tenant', to='school_user.Tenant')),
            ],
            options={
                'ordering': ('display_payslip', 'serial_no', 'id'),
            },
        ),
        migrations.CreateModel(
            name='salary_payment_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(max_length=8)),
                ('display_payslip', models.BooleanField(default=True)),
                ('serial_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salary_name', models.TextField()),
                ('account_id', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='staff_salary_definition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('epfEpsEmployer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffSalary_epfEpsEmployer', to='school_salary.epf_eps_employer')),
                ('esiEmployer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffSalary_esiEmployer', to='school_salary.esi_employer')),
                ('monthly_salary', models.ManyToManyField(db_index=True, related_name='staffSalary_monthlySalary', to='school_salary.monthly_salary')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffSalary_salary_teacher_teacher', to='school_teacher.Teacher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffSalary_salary_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='staff_salary_payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.CharField(max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffSalaryPayment_salary_teacher_teacher', to='school_teacher.Teacher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffSalaryPayment_salary_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='yearly_salary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('month', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearlySalary_salary_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='yearly_salary_list',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_payslip', models.BooleanField(default=True)),
                ('serial_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearlySalaryList_salary_account_account', to='school_account.Account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearlySalaryList_salary_user_tenant', to='school_user.Tenant')),
                ('yearly_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearlySalaryList_monthlySalary', to='school_salary.yearly_salary')),
            ],
            options={
                'ordering': ('display_payslip', 'serial_no', 'id'),
            },
        ),
        migrations.AddField(
            model_name='staff_salary_definition',
            name='yearly_salary',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='staffSalary_yearlySalary', to='school_salary.yearly_salary'),
        ),
        migrations.AddField(
            model_name='salary_payment_list',
            name='salary_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaryPaymentList_staffSalaryPayment', to='school_salary.staff_salary_payment'),
        ),
        migrations.AddField(
            model_name='salary_payment_list',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaryPaymentList_salary_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AddField(
            model_name='cadre_default_salary',
            name='epfEpsEmployer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadreDefaultSalary_epfEpsEmployer', to='school_salary.epf_eps_employer'),
        ),
        migrations.AddField(
            model_name='cadre_default_salary',
            name='esiEmployer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadreDefaultSalary_esiEmployer', to='school_salary.esi_employer'),
        ),
        migrations.AddField(
            model_name='cadre_default_salary',
            name='monthly_salary',
            field=models.ManyToManyField(db_index=True, related_name='cadreDefaultSalary_monthlySalary', to='school_salary.monthly_salary'),
        ),
        migrations.AddField(
            model_name='cadre_default_salary',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadreDefaultSalary_salary_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AddField(
            model_name='cadre_default_salary',
            name='yearly_salary',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='cadreDefaultSalary_yearlySalary', to='school_salary.yearly_salary'),
        ),
        migrations.AlterUniqueTogether(
            name='cadre_default_salary',
            unique_together=set([('cadre', 'year', 'tenant')]),
        ),
    ]
