# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epf_eps_employer',
            old_name='epf_ceiling',
            new_name='salary_ceiling',
        ),
        migrations.RemoveField(
            model_name='epf_eps_employer',
            name='eps_ceiling',
        ),
    ]
