# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_salary', '0002_auto_20170224_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epf_eps_employer',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='epf_eps_employer',
            unique_together=set([('name', 'is_active', 'tenant')]),
        ),
    ]
