# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0020_auto_20170223_2009'),
        ('school_salary', '0003_auto_20170224_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_statutory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('statutory_type', models.CharField(max_length=3)),
                ('rule', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Statutory rule')),
                ('is_active', models.BooleanField(default=True)),
                ('ceiling', models.PositiveIntegerField(blank=True, null=True)),
                ('predefined', models.PositiveIntegerField(blank=True, null=True)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeStatutory_salary_account_account', to='school_account.Account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeStatutory_salary_user_tenant', to='school_user.Tenant')),
            ],
        ),
    ]
