# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0013_auto_20170219_1615'),
        ('school_salary', '0004_employee_statutory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadre_default_salary',
            name='cadre_type',
            field=models.CharField(choices=[('Master', 'Master'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Principal', 'Principal'), ('Account', 'Account'), ('Collector', 'Fee Collector')], db_index=True, default='Teacher', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadre_default_salary',
            name='epfEmployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadreDefaultSalary_epfEmployee', to='school_salary.employee_statutory'),
        ),
        migrations.AddField(
            model_name='cadre_default_salary',
            name='esiEmployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadreDefaultSalary_esiEmployee', to='school_salary.employee_statutory'),
        ),
        migrations.AddField(
            model_name='staff_salary_definition',
            name='epfEmployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffSalary_epfEmployee', to='school_salary.employee_statutory'),
        ),
        migrations.AddField(
            model_name='staff_salary_definition',
            name='esiEmployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffSalary_esiEmployee', to='school_salary.employee_statutory'),
        ),
        migrations.AddField(
            model_name='staff_salary_definition',
            name='staff_type',
            field=models.CharField(choices=[('Master', 'Master'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Principal', 'Principal'), ('Account', 'Account'), ('Collector', 'Fee Collector')], db_index=True, default='Teacher', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='staff_salary_definition',
            unique_together=set([('staff', 'year', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='staff_salary_payment',
            unique_together=set([('staff', 'month', 'year', 'tenant')]),
        ),
    ]
