# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_salary', '0005_auto_20170224_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadre_default_salary',
            name='slug',
        ),
    ]
