# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_account', '0020_auto_20170223_2009'),
        ('school_salary', '0006_remove_cadre_default_salary_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='edli_employer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('rule', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Statutory rule')),
                ('ceiling', models.PositiveIntegerField(blank=True, null=True)),
                ('edli_predefined', models.PositiveIntegerField(blank=True, null=True)),
                ('edli_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('edliac_min', models.PositiveIntegerField(blank=True, null=True)),
                ('edliac_predefined', models.PositiveIntegerField(blank=True, null=True)),
                ('edliac_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('edli_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edliEmployer_salary_account_account', to='school_account.Account')),
                ('edliac_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edliacEmployer_salary_account_account', to='school_account.Account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edliEmployer_salary_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.RemoveField(
            model_name='salary_payment_list',
            name='account_id',
        ),
        migrations.AddField(
            model_name='salary_payment_list',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salaryPaymentList_salary_account_account', to='school_account.Account'),
            preserve_default=False,
        ),
    ]
