# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_salary', '0008_auto_20170225_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_salary_payment',
            old_name='total_amount',
            new_name='gross',
        ),
        migrations.AddField(
            model_name='staff_salary_payment',
            name='employee_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_salary_payment',
            name='employer_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_salary_payment',
            name='net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
