# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 04:42
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor_master', '0027_service_sales_rate'),
        ('distributor_user', '0014_auto_20170824_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_line_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_sku', models.CharField(max_length=20)),
                ('service_hsn', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('unit_id', models.BigIntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('unit_multi', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('quantity_returned', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_tax_included', models.BooleanField(default=False)),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cgst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sgst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('igst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('line_before_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiceLineItem_serviceSales_master_service', to='distributor_master.Service')),
            ],
        ),
        migrations.CreateModel(
            name='service_invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.PositiveIntegerField(db_index=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('warehouse_address', models.TextField()),
                ('warehouse_state', models.CharField(max_length=4)),
                ('warehouse_city', models.CharField(max_length=50)),
                ('warehouse_pin', models.CharField(max_length=8)),
                ('payment_mode_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('payment_mode_name', models.CharField(blank=True, max_length=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('roundoff', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceInvoice_sales_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviceInvoice_retailsales_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='service_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceLineItem_serviceInvoice', to='service_sales.service_invoice'),
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceLineItem_serviceSales_user_tenant', to='distributor_user.Tenant'),
        ),
    ]
