# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-11 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_sales', '0002_auto_20171128_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_line_item',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='invoice_line_item',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
