# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0003_tenant_maintain_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('can_create_master', models.BooleanField()),
                ('can_authorize_master', models.BooleanField()),
                ('can_create_purchase', models.BooleanField()),
                ('can_authorize_purchase', models.BooleanField()),
                ('can_create_sales', models.BooleanField()),
                ('can_authorize_sales', models.BooleanField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userPermission_tenant', to='distributor_user.Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userPermission_user', to='distributor_user.Tenant')),
            ],
        ),
    ]
