# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0005_auto_20170614_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='address_1',
            field=models.CharField(max_length=100, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='city',
            field=models.CharField(max_length=30, verbose_name='City'),
        ),
    ]
