# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0006_auto_20170615_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenant_payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('no_customers', models.PositiveSmallIntegerField(default=1)),
                ('no_sms', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='tenant',
            name='no_of_profile',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant_payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenantPayment_tenant', to='distributor_user.Tenant'),
        ),
    ]
