# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0007_auto_20170616_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Distributor'), (2, 'Retailer'), (3, 'Both Retail & Distributor')], default=1),
        ),
    ]
