# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0009_auto_20170630_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='paid_until',
            new_name='paid_due',
        ),
        migrations.AddField(
            model_name='tenant_payment',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant_payment',
            name='payment_no',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
