# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0010_auto_20170701_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='cst',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='gst',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TIN Number'),
        ),
    ]
