# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0011_auto_20170709_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='dl_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 1'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='dl_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 2'),
        ),
    ]
