# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-24 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0016_user_user_authorization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_authorization',
        ),
    ]
