# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-26 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0019_auto_20171126_1335'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
