# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-22 09:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0021_auto_20171128_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='distributor_sales_policy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
