# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('remarks', models.TextField(blank=True)),
                ('group', models.CharField(blank=True, max_length=15)),
                ('slug', models.SlugField(max_length=20)),
                ('key', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('date', 'group'),
            },
        ),
        migrations.CreateModel(
            name='journalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=6, verbose_name='Transaction type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ('journal', 'transaction_type'),
            },
        ),
    ]
