# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution_user', '0001_initial'),
        ('distribution_master', '0006_auto_20160915_0308'),
        ('distribution_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntry_accountChart', to='distribution_master.accountChart'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntry_journal', to='distribution_accounts.Journal'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalentry_master_user_tenant', to='distribution_user.Tenant'),
        ),
        migrations.AddField(
            model_name='journal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_master_user_tenant', to='distribution_user.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together=set([('journal', 'account')]),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set([('key', 'tenant')]),
        ),
    ]
