# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_accounts', '0003_auto_20160915_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='slug',
            field=models.SlugField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='key',
            field=models.CharField(max_length=10),
        ),
    ]
