# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_accounts', '0006_auto_20160917_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='group',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
