# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_accounts', '0007_auto_20160917_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountchart',
            options={'ordering': ['account_type', 'name']},
        ),
    ]
