# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_user', '0001_initial'),
        ('distribution_accounts', '0008_auto_20160923_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Payment Mode Name')),
                ('default', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Default Payment Mode ?')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentMode_accountChart', to='distribution_accounts.accountChart')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentmode_account_user_tenant', to='distribution_user.Tenant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='paymentmode',
            unique_together=set([('name', 'payment_account', 'tenant')]),
        ),
    ]
