# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_accounts', '0009_auto_20160928_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmode',
            unique_together=set([('name', 'tenant'), ('payment_account', 'tenant')]),
        ),
    ]
