# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_user', '0001_initial'),
        ('distribution_accounts', '0010_auto_20160930_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='journalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalgroup_account_user_tenant', to='distribution_user.Tenant')),
            ],
        ),
        migrations.AlterModelOptions(
            name='paymentmode',
            options={},
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='slug',
            field=models.SlugField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='journal_journalgroup', to='distribution_accounts.journalGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Payment Mode Name'),
        ),
        migrations.AlterUniqueTogether(
            name='journalgroup',
            unique_together=set([('name', 'tenant')]),
        ),
    ]
