# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_accounts', '0011_auto_20161004_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_account_user_tenant', to='distribution_accounts.journalGroup'),
        ),
    ]
