# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_accounts', '0013_journalgroup_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalgroup',
            old_name='default',
            new_name='current_period',
        ),
    ]
