# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_accounts', '0015_auto_20161004_1416'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountchart',
            unique_together=set([('key', 'tenant')]),
        ),
    ]
