# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_accounts', '0016_auto_20161014_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_journalgroup', to='distribution_accounts.journalGroup'),
        ),
    ]
