# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_accounts', '0017_auto_20161023_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountchart',
            name='key',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='accountchart',
            name='slug',
            field=models.SlugField(),
        ),
    ]
