# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_user', '0017_tenant_no_of_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='from_communication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromCommunication_communication_user_user', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromCommunication_communication_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='to_comminucation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('from_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toCommunication_fromCommunication', to='school_communication.from_communication')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toCommunication_communication_user_tenant', to='school_user.Tenant')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toCommunication_communication_user_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
