# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-05 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

#    dependencies = [
#        ('school_user', '0002_remove_user_user_id'),
#    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Name of the branch')),
                ('key', models.CharField(db_index=True, max_length=10)),
                ('slug', models.SlugField(max_length=35)),
                ('address_line_1', models.TextField(blank=True, verbose_name='Address Line 1')),
                ('address_line_2', models.TextField(blank=True, verbose_name='Address Line 2')),
                ('state', models.CharField(blank=True, max_length=30)),
                ('pincode', models.PositiveIntegerField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_genadmin_user_tenant', to='school_user.Tenant')),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='class_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=40)),
                #('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classGroup_branch', to='school_genadmin.Branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classGroup_genadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Subject Name')),
                ('key', models.CharField(db_index=True, max_length=10)),
                ('slug', models.SlugField(max_length=35)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_genadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('key', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='class_group',
            unique_together=set([('name', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set([('key', 'tenant')]),
        ),
    ]
