# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0002_remove_user_user_id'),
        ('school_genadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('house_motto', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_genadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='class_group',
            name='name',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='class_group',
            name='slug',
            field=models.SlugField(),
        ),
        # migrations.RemoveField(
        #     model_name='class_group',
        #     name='branch',
        # ),
        migrations.AlterUniqueTogether(
            name='class_group',
            unique_together=set([('name', 'tenant')]),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together=set([('name', 'tenant')]),
        ),
    ]
