# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0002_auto_20161206_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('name', 'tenant')]),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='key',
        ),        
    ]
