# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-18 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0004_auto_20161217_0924'),
        ('school_genadmin', '0004_auto_20161208_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='annual_calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('event', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('key', models.CharField(db_index=True, max_length=10)),
                ('slug', models.SlugField(max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annualCalender_genadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='annual_calender',
            unique_together=set([('key', 'tenant')]),
        ),
    ]
