# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0005_auto_20161218_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_calender',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        # migrations.RemoveField(
        #     model_name='annual_calender',
        #     name='key',
        # ),
        migrations.RemoveField(
            model_name='annual_calender',
            name='remarks',
        ),
        migrations.AlterUniqueTogether(
            name='annual_calender',
            unique_together=set([('slug', 'tenant')]),
        ),
    ]
