# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0006_auto_20161227_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annual_calender',
            name='key',
        ),
        migrations.AlterField(
            model_name='annual_calender',
            name='event',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='annual_calender',
            name='slug',
            field=models.SlugField(max_length=75),
        ),
    ]
