# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0008_auto_20170104_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='slug',
            field=models.SlugField(max_length=45),
        ),
    ]
