# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0009_auto_20170104_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='annual_calender',
            name='event_type',
            field=models.CharField(choices=[('E', 'Exam'), ('H', 'Holiday'), ('O', 'Other')], default='H', max_length=1, verbose_name='Event type'),
        ),
    ]
