# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0011_auto_20170123_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Academic Year: If year is 2016-17, enter 2016'),
        ),
    ]
