# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0012_auto_20170123_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_year',
            name='end',
            field=models.DateField(default='2017-03-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academic_year',
            name='start',
            field=models.DateField(default='2016-04-01'),
            preserve_default=False,
        ),
    ]
