# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0013_auto_20170125_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='annual_holiday_rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('week', models.DateTimeField()),
                ('day', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=80)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annualHolidayRules_genadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='annual_calender',
            name='attendance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Working Day'), (2, 'Non working day')], default='1', verbose_name='Attendance type'),
        ),
        migrations.AlterField(
            model_name='annual_calender',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Exam'), (2, 'Holiday'), (3, 'Excption'), (4, 'Others')], default='1', verbose_name='Event type'),
        ),
        migrations.AlterUniqueTogether(
            name='annual_calender',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='annual_holiday_rules',
            unique_together=set([('slug', 'tenant')]),
        ),
    ]
