# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0014_auto_20170128_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annual_holiday_rules',
            name='week',
        ),
        migrations.AlterField(
            model_name='annual_calender',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Holiday'), (2, 'Exam'), (3, 'Excption'), (4, 'Others')], default='1', verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='annual_holiday_rules',
            name='day',
            field=models.CharField(db_index=True, max_length=2),
        ),
    ]
