# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0016_annual_holiday_rules_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annual_holiday_rules',
            name='day',
        ),
    ]
