# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0017_remove_annual_holiday_rules_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='annual_holiday_rules',
            name='day',
            field=models.PositiveSmallIntegerField(db_index=True, default=5),
        ),
    ]
