# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-01 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0018_annual_holiday_rules_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_calender',
            name='attendance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Working Day'), (2, 'Non working day')], default='2', verbose_name='Attendance type'),
        ),
    ]
