# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-04 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0019_auto_20170201_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='class_group',
        ),
    ]
