# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0020_auto_20170209_1119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academic_year',
            unique_together=set([('year', 'tenant'), ('end', 'tenant'), ('start', 'tenant')]),
        ),
    ]
