# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0023_auto_20170226_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='end_year',
            field=models.PositiveSmallIntegerField(default=2020, verbose_name='Batch Ends On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='start_year',
            field=models.PositiveSmallIntegerField(default=2010, verbose_name='Batch Starts On'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='class_group',
            name='standard',
            field=models.IntegerField(choices=[(-6, 'Lower Nusrsery'), (-5, 'Nursery'), (-4, 'Upper Nursery'), (-3, 'Lower KG'), (-2, 'Kindergarten'), (-1, 'Upper KG'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Foure'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten'), (11, 'Eleven'), (12, 'Twelve')], db_index=True),
        ),
    ]
