# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0024_auto_20170228_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade_table',
            old_name='marks',
            new_name='max_mark',
        ),
        migrations.AddField(
            model_name='grade_table',
            name='min_mark',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
