# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0025_auto_20170301_1934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade_table',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='grade_table',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='grade_table',
        ),
    ]
