# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0027_auto_20170304_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board',
            name='show_until',
            field=models.DateField(blank=True),
        ),
    ]
