# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0028_auto_20170320_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_additional',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
    ]
