# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0029_auto_20170323_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board',
            name='show_from',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='show_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
