# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0030_auto_20170325_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board',
            name='show_from',
            field=models.DateField(verbose_name='Notice Date'),
        ),
    ]
