# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0031_auto_20170330_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_calender',
            name='attendance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Working Day'), (2, 'Non working day')], verbose_name='Attendance type'),
        ),
        migrations.AlterField(
            model_name='annual_calender',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Holiday'), (2, 'Exam'), (3, 'Exception'), (4, 'Others')], verbose_name='Event type'),
        ),
    ]
