# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0032_auto_20170407_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual_calender',
            name='event',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='annual_calender',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Holiday'), (2, 'Exam'), (3, 'Exception'), (4, 'Others'), (5, 'Vacation')], verbose_name='Event type'),
        ),
    ]
