# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0003_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cgst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cgst', to='distributor_master.tax_structure'),
        ),
        migrations.AddField(
            model_name='product',
            name='igst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_igst', to='distributor_master.tax_structure'),
        ),
        migrations.AddField(
            model_name='product',
            name='sgst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sgst', to='distributor_master.tax_structure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_vat', to='distributor_master.tax_structure'),
        ),
    ]
