# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0004_auto_20170529_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_zone', to='distributor_master.Zone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cgst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_cgst', to='distributor_master.tax_structure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_unit', to='distributor_master.Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_group', to='distributor_master.Group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='igst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_igst', to='distributor_master.tax_structure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_manufacturer', to='distributor_master.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sgst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sgst', to='distributor_master.tax_structure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_vat', to='distributor_master.tax_structure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'No VAT'), (2, 'On MRP'), (3, 'On Cost Price')], default=3, null=True, verbose_name='VAT type'),
        ),
    ]
