# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0004_user_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributor_master', '0005_auto_20170529_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseUser_master_user_tenant', to='distributor_user.Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseUser_master_user_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_sales_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse_user',
            name='warehouse',
            field=models.ManyToManyField(to='distributor_master.Warehouse'),
        ),
    ]
