# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0008_auto_20170614_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_customer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retail_customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
