# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0007_auto_20170616_1206'),
        ('distributor_master', '0009_auto_20170616_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_sales_rate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tentative_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSalesRate_product', to='distributor_master.Product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSalesRate_master_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSalesRate_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product_price',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='product_price',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_price',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='product_price',
        ),
        migrations.AlterUniqueTogether(
            name='product_sales_rate',
            unique_together=set([('product', 'warehouse', 'tenant')]),
        ),
    ]
