# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0010_auto_20170617_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_sales_rate',
            old_name='tentative_sales',
            new_name='tentative_sales_rate',
        ),
        migrations.AlterUniqueTogether(
            name='product_sales_rate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='product_sales_rate',
            name='warehouse',
        ),
    ]
