# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0011_auto_20170618_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sales_rate',
            name='is_tax_included',
            field=models.BooleanField(default=True),
        ),
    ]
