# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0007_auto_20170616_1206'),
        ('distributor_master', '0012_product_sales_rate_is_tax_included'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_sales_rate',
            unique_together=set([('product', 'tenant')]),
        ),
    ]
