# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0013_auto_20170618_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
