# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0014_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
