# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0017_auto_20170625_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
