# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0019_auto_20170713_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
