# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0020_auto_20170723_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dl_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dl_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 2'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='dl_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 1'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='dl_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 2'),
        ),
    ]
