# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0023_auto_20170824_0723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_sales_rate',
            unique_together=set([]),
        ),
    ]
