# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 10:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0024_auto_20170927_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
