# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 06:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0014_auto_20170824_0723'),
        ('distributor_master', '0025_product_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=20)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('hsn_code', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cgst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_cgst', to='distributor_master.tax_structure')),
                ('default_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_unit', to='distributor_master.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='service_group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceGroup_master_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product_attribute',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='product_attribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='product_attribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_attribute',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='product_attribute',
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_group', to='distributor_master.service_group'),
        ),
        migrations.AddField(
            model_name='service',
            name='igst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_igst', to='distributor_master.tax_structure'),
        ),
        migrations.AddField(
            model_name='service',
            name='sgst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_sgst', to='distributor_master.tax_structure'),
        ),
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_master_user_tenant', to='distributor_user.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='service_group',
            unique_together=set([('name', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('sku', 'tenant')]),
        ),
    ]
