# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0014_auto_20170824_0723'),
        ('distributor_master', '0026_auto_20171121_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_sales_rate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tentative_sales_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_tax_included', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceSalesRate_product', to='distributor_master.Service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceSalesRate_master_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
    ]
