# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0027_service_sales_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_sales_rate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceSalesRate_service', to='distributor_master.Service'),
        ),
    ]
