# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0029_auto_20171201_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cst',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='cst',
        ),
        migrations.AddField(
            model_name='customer',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
