# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0004_auto_20170523_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_line_item',
            name='unit_multi',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
