# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0005_receipt_line_item_unit_multi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_payment',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasePayment_purchase_accounts_paymentMode', to='distributor_account.payment_mode'),
        ),
        migrations.AlterField(
            model_name='purchase_receipt',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseReceipt_purchase_master_vendor', to='distributor_master.Vendor'),
        ),
        migrations.AlterField(
            model_name='purchase_receipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseReceipt_purchase_master_warehouse', to='distributor_master.Warehouse'),
        ),
        migrations.AlterField(
            model_name='receipt_line_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiptLineItem_purchase_master_product', to='distributor_master.Product'),
        ),
    ]
