# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0006_auto_20170529_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_line_item',
            name='line_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt_line_item',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
