# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0007_auto_20170601_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_payment',
            name='payment_mode_name',
            field=models.CharField(db_index=True, default=1, max_length=20, verbose_name='Payment Mode Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt_line_item',
            name='discount2_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipt_line_item',
            name='discount2_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
