# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0010_auto_20170607_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_payment',
            name='payment_mode_name',
            field=models.CharField(max_length=20, verbose_name='Payment Mode Name'),
        ),
    ]
