# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0014_purchase_receipt_vendor_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_receipt',
            name='grand_discount',
        ),
        migrations.RemoveField(
            model_name='purchase_receipt',
            name='grand_discount_type',
        ),
        migrations.AddField(
            model_name='purchase_receipt',
            name='gst_type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
