# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0013_auto_20170614_1902'),
        ('distributor_user', '0006_auto_20170615_1818'),
        ('distributor_purchase', '0015_auto_20170616_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_line_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentLineItem_paymentMode', to='distributor_account.payment_mode')),
            ],
        ),
        migrations.AddField(
            model_name='purchase_receipt',
            name='grand_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='purchase_receipt',
            name='grand_discount_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment_line_item',
            name='purchase_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentLineItem_purchaseReceipt', to='distributor_purchase.purchase_receipt'),
        ),
        migrations.AddField(
            model_name='payment_line_item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentLineItem_purchase_user_tenant', to='distributor_user.Tenant'),
        ),
    ]
