# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0016_auto_20170616_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_line_item',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='payment_line_item',
            name='purchase_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paymentLineItem_purchasePayment', to='distributor_purchase.purchase_payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt_line_item',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='purchase_receipt',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
