# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0018_auto_20170616_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_line_item',
            name='product_hsn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
