# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0019_receipt_line_item_product_hsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_receipt',
            name='supplier_invoice',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
