# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0024_auto_20170710_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_line_item',
            name='free_with_tax',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt_line_item',
            name='free_without_tax',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
