# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0028_auto_20170710_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_line_item',
            name='quantity_returned',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
