# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0030_receipt_line_item_free_with_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit_note',
            name='dl_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 1'),
        ),
        migrations.AddField(
            model_name='debit_note',
            name='dl_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 2'),
        ),
        migrations.AddField(
            model_name='purchase_receipt',
            name='dl_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 1'),
        ),
        migrations.AddField(
            model_name='purchase_receipt',
            name='dl_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 2'),
        ),
    ]
