# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0031_auto_20170731_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_receipt',
            name='roundoff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
