# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0032_purchase_receipt_roundoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_receipt',
            name='supplier_invoice',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
