# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0033_auto_20170904_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit_note',
            name='vendor_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase_receipt',
            name='vendor_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='receipt_line_item',
            name='product_hsn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
