# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0014_auto_20170824_0723'),
        ('distributor_master', '0023_auto_20170824_0723'),
        ('distributor_purchase', '0034_auto_20170909_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_line_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(max_length=50)),
                ('product_hsn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('unit_multi', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_delivered', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('free_with_tax', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_type', models.PositiveSmallIntegerField(default=0)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount2_type', models.PositiveSmallIntegerField(default=0)),
                ('discount2_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cgst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sgst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('igst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('line_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderLineItem_purchase_master_product', to='distributor_master.Product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderLineItem_purchaseOrder', to='distributor_purchase.purchase_receipt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderLineItem_purchase_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.PositiveIntegerField(db_index=True)),
                ('supplier_order', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('vendor_state', models.CharField(blank=True, max_length=4, null=True)),
                ('vendor_city', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_pin', models.CharField(blank=True, max_length=8, null=True)),
                ('vendor_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('warehouse_address', models.TextField()),
                ('warehouse_state', models.CharField(max_length=4)),
                ('warehouse_city', models.CharField(max_length=50)),
                ('warehouse_pin', models.CharField(max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roundoff', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_by', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseOrder_purchase_user_tenant', to='distributor_user.Tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseOrder_purchase_master_vendor', to='distributor_master.Vendor')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseOrder_purchase_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
    ]
