# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0035_order_line_item_purchase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line_item',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='order_line_item',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='order_line_item',
            name='manufacturing_date',
        ),
        migrations.RemoveField(
            model_name='order_line_item',
            name='serial_no',
        ),
        migrations.AlterField(
            model_name='order_line_item',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderLineItem_purchaseOrder', to='distributor_purchase.purchase_order'),
        ),
    ]
