# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0037_auto_20170916_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_receipt',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
