# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0038_purchase_receipt_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_receipt',
            name='inventory_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='receipt_line_item',
            name='free_with_tax',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receipt_line_item',
            name='product_sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt_line_item',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receipt_line_item',
            name='quantity_returned',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receipt_line_item',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receipt_line_item',
            name='unit_multi',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, null=True),
        ),
    ]
