# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0040_auto_20171222_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_line_item',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchase_payment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receipt_line_item',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
