# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0022_tenant_distributor_sales_policy'),
        ('distributor_purchase', '0041_auto_20180131_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_mode_id', models.BigIntegerField(db_index=True)),
                ('payment_mode_name', models.CharField(max_length=20, verbose_name='Payment Mode Name')),
                ('vendorid', models.BigIntegerField(db_index=True)),
                ('payment_reason_details', models.CharField(max_length=200)),
                ('payment_reason_type', models.PositiveSmallIntegerField(db_index=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheque_rtgs_number', models.CharField(blank=True, max_length=30, null=True)),
                ('paid_on', models.DateField(blank=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherPayment_purchase_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
    ]
