# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-28 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0031_auto_20180124_2052'),
        ('distributor_user', '0022_tenant_distributor_sales_policy'),
        ('distributor_purchase', '0042_other_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(blank=True, max_length=12)),
                ('note_type', models.CharField(choices=[(1, 'Inventory Return'), (2, 'Non-inventory Adjustment')], max_length=12)),
                ('supplier_note_no', models.CharField(blank=True, max_length=200, null=True)),
                ('adjustmnet_receipt_no', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('vendor_state', models.CharField(blank=True, max_length=4, null=True)),
                ('vendor_city', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_pin', models.CharField(blank=True, max_length=8, null=True)),
                ('dl_1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 1')),
                ('dl_2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Drug License 2')),
                ('warehouse_address', models.TextField()),
                ('warehouse_state', models.CharField(max_length=4)),
                ('warehouse_city', models.CharField(max_length=50)),
                ('warehouse_pin', models.CharField(max_length=8)),
                ('gst_type', models.PositiveSmallIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseReturn_purchase_user_tenant', to='distributor_user.Tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseReturn_purchase_master_vendor', to='distributor_master.Vendor')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseReturn_purchase_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='return_line_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(max_length=50)),
                ('product_hsn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('unit_multi', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('real_purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tentative_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MRP')),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cgst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sgst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('igst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('line_taxable_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returnLineItem_purchase_master_product', to='distributor_master.Product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnLineItem_purchaseReturn', to='distributor_purchase.purchase_return')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnLineItem_purchase_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.RemoveField(
            model_name='debit_note',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='debit_note',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='debit_note',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='debit_note_line_item',
            name='debit_note',
        ),
        migrations.RemoveField(
            model_name='debit_note_line_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='debit_note_line_item',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='debit_note',
        ),
        migrations.DeleteModel(
            name='debit_note_line_item',
        ),
    ]
