# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-21 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0043_auto_20180228_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_line_item',
            name='unit_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_return',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='return_line_item',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
