# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0045_auto_20180323_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return_line_item',
            old_name='unit',
            new_name='unit_symbol',
        ),
    ]
