# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_purchase', '0046_auto_20180323_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_return',
            name='roundoff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='purchase_return',
            name='vendor_gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='roundoff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='purchase_receipt',
            name='roundoff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
