# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 18:54
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor_account', '0005_tax_transaction'),
        ('distributor_master', '0002_auto_20170517_1647'),
        ('distributor_user', '0002_auto_20170517_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_line_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(max_length=50)),
                ('vat_type', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('free_without_tax', models.PositiveSmallIntegerField(default=0)),
                ('free_with_tax', models.PositiveSmallIntegerField(default=0)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tentative_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MRP')),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('discount_type', models.PositiveSmallIntegerField(default=0)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceLineItem_sales_master_product', to='distributor_master.Product')),
            ],
        ),
        migrations.CreateModel(
            name='sales_invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.PositiveIntegerField(db_index=True)),
                ('supplier_invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('customer_name', models.CharField(db_index=True, max_length=200)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_state', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_pin', models.CharField(blank=True, max_length=8, null=True)),
                ('warehouse_address', models.TextField()),
                ('warehouse_state', models.CharField(max_length=4)),
                ('warehouse_city', models.CharField(max_length=50)),
                ('warehouse_pin', models.CharField(max_length=8)),
                ('grand_discount_type', models.PositiveSmallIntegerField(default=0)),
                ('grand_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payable_by', models.DateField(blank=True, null=True)),
                ('final_payment_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesInvoice_sales_master_customer', to='distributor_master.Customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesInvoice_sales_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesInvoice_sales_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='sales_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheque_rtgs_number', models.CharField(blank=True, max_length=30, null=True)),
                ('paid_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('final_payment_delay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesPayment_sales_accounts_paymentMode', to='distributor_account.payment_mode')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesPayment_salesInvoice', to='distributor_sales.sales_invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesPayment_sales_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='sales_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceLineItem_salesInvoice', to='distributor_sales.sales_invoice'),
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiceLineItem_sales_master_taxStructure', to='distributor_master.tax_structure'),
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceLineItem_sales_user_tenant', to='distributor_user.Tenant'),
        ),
    ]
