# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_line_item',
            name='tax',
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
