# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0004_remove_sales_invoice_supplier_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_payment',
            old_name='amount_paid',
            new_name='amount_received',
        ),
    ]
