# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0008_auto_20170601_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_line_item',
            name='cgst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='cgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='igst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='igst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='sgst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='invoice_line_item',
            name='sgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='cgsttotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='igsttotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='sgsttotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='taxtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
