# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0010_sales_payment_payment_mode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_line_item',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales_invoice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales_payment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
