# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0006_auto_20170615_1818'),
        ('distributor_sales', '0012_sales_invoice_customer_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_line_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentLineItem_salesInvoice', to='distributor_sales.sales_invoice')),
                ('sales_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentLineItem_salesPayment', to='distributor_sales.sales_payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentLineItem_sales_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
    ]
