# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0013_payment_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_line_item',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
