# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0015_auto_20170616_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_payment',
            name='paid_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
