# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 09:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0017_invoice_line_item_product_hsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_line_item',
            name='other_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
