# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 07:05
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0010_auto_20170701_1225'),
        ('distributor_master', '0018_auto_20170705_1443'),
        ('distributor_sales', '0018_auto_20170703_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_credit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerCredit_sales_master_customer', to='distributor_master.Customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerCredit_sales_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='return_line_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(max_length=50)),
                ('product_hsn', models.CharField(blank=True, max_length=20, null=True)),
                ('vat_type', models.CharField(max_length=15)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unit', models.CharField(max_length=20)),
                ('unit_multi', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('return_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tentative_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MRP')),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cgst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sgst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('igst_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('line_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returnLineItem_sales_master_product', to='distributor_master.Product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnLineItem_salesReturn', to='distributor_sales.sales_invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnLineItem_sales_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='sales_return',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('return_type', models.PositiveSmallIntegerField(default=1)),
                ('return_id', models.PositiveIntegerField(db_index=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('customer_name', models.CharField(db_index=True, max_length=200)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_state', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_pin', models.CharField(blank=True, max_length=8, null=True)),
                ('customer_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('warehouse_address', models.TextField()),
                ('warehouse_state', models.CharField(max_length=4)),
                ('warehouse_city', models.CharField(max_length=50)),
                ('warehouse_pin', models.CharField(max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igsttotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesReturn_sales_master_customer', to='distributor_master.Customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesReturn_salesInvoice', to='distributor_sales.sales_invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesReturn_sales_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesReturn_sales_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customer_credit',
            unique_together=set([('customer', 'tenant')]),
        ),
    ]
