# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0019_auto_20170706_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_line_item',
            name='sales_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnLineItem_salesReturn', to='distributor_sales.sales_return'),
        ),
    ]
