# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0022_auto_20170708_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_line_item',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoice_line_item',
            name='quantity_returned',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='return_line_item',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
