# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0026_auto_20170710_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_invoice',
            name='is_b2b_registered',
        ),
    ]
