# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0030_auto_20170811_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='roundoff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
