# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0031_sales_invoice_roundoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_line_item',
            name='product_hsn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='return_line_item',
            name='product_hsn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales_invoice',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sales_return',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
    ]
