# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0032_auto_20170909_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='customer_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sales_return',
            name='customer_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
