# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-24 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0033_auto_20171223_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_invoice',
            name='invoice_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
