# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0035_auto_20180112_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_payment',
            name='is_finalized',
            field=models.BooleanField(default=True),
        ),
    ]
