# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0036_sales_payment_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_return',
            name='return_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesReturn_returnInvoice', to='distributor_sales.sales_invoice'),
        ),
    ]
