# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-23 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0038_sales_invoice_return_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_return',
            name='return_type',
            field=models.BigIntegerField(),
        ),
    ]
