# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-10 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0040_auto_20180123_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_invoice',
            name='invoice_manufacturer',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
