# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-10 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_sales', '0041_sales_invoice_invoice_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_invoice',
            old_name='invoice_manufacturer',
            new_name='manufacturer',
        ),
    ]
