# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-01 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_teacher', '0009_teacher_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('key', models.CharField(max_length=5)),
                ('slug', models.SlugField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveType_hr_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='teacher_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ispresent', models.CharField(db_index=True, max_length=12)),
                ('remarks', models.TextField()),
                ('slug', models.SlugField()),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAttendance_leaveType', to='school_hr.leave_type')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAttendance_hr_teacher_teacher', to='school_teacher.Teacher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAttendance_hr_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teacher_attendance',
            unique_together=set([('teacher', 'date', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='leave_type',
            unique_together=set([('key', 'tenant'), ('name', 'tenant')]),
        ),
    ]
