# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_type',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
