# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_hr', '0002_auto_20170201_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_attendance',
            name='leave_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherAttendance_leaveType', to='school_hr.leave_type'),
        ),
    ]
