# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_hr', '0004_auto_20170215_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadre_leave',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leave_type',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff_cadre',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff_cadre_linking',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher_attendance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
