# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_hr', '0005_auto_20170219_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_attendance',
            name='ispresent',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='teacher_attendance',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherAttendance_leaveType', to='school_hr.leave_type'),
        ),
    ]
