# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_hr', '0006_auto_20170220_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_cadre_linking',
            name='year',
            field=models.PositiveSmallIntegerField(default=2016),
            preserve_default=False,
        ),
    ]
