# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_hr', '0010_auto_20170304_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_type',
            name='leave_type',
            field=models.CharField(choices=[('L)P', 'Loss of Pay'), ('O', 'Others')], default='O', max_length=3),
        ),
    ]
