# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_hr', '0011_leave_type_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_type',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='leave_type',
            name='leave_type_option',
            field=models.CharField(choices=[('LOP', 'Loss of Pay'), ('O', 'Others')], default='O', max_length=3),
        ),
    ]
