# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_hr', '0013_auto_20170311_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_attendance',
            name='attendance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Mispunch')], default=1),
        ),
    ]
