# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_library', '0002_auto_20170102_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='issue_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookIssue_issuePeriod', to='school_library.issue_period'),
        ),
        migrations.AlterField(
            model_name='book_return',
            name='is_late',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='issue_period',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issuePeriod_library_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='issue_period',
            unique_together=set([]),
        ),
    ]
