# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0048_auto_20170419_2114'),
        ('school_library', '0004_auto_20170219_1615'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book_return',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='book_return',
            name='issue_details',
        ),
        migrations.RemoveField(
            model_name='book_return',
            name='return_entry_by',
        ),
        migrations.RemoveField(
            model_name='book_return',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='librarian',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='librarian',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='library',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='library',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='library',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='issue_period',
            name='slug',
        ),
        migrations.AddField(
            model_name='book',
            name='publishion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book_issue',
            name='issued_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookIssue_library_eduacmin_classSection', to='school_eduadmin.class_section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_issue',
            name='returned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='is_late',
            field=models.NullBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='issued_on',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='returned',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='book_issue',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='book_return',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_issued',
        ),
        migrations.RemoveField(
            model_name='book',
            name='key',
        ),
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='issue_period',
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='key',
        ),
        migrations.RemoveField(
            model_name='book_issue',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
