# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_library', '0005_auto_20170422_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity_issued',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='school_book_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='School Book ID/Key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_library_genadmin_subject', to='school_genadmin.Subject'),
        ),
    ]
