# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_library', '0006_auto_20170424_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity_issued',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity_available',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
