# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_genadmin', '0001_initial'),
        ('school_user', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, verbose_name='Class Name with section')),
                ('room', models.CharField(blank=True, max_length=15, verbose_name='Room name/no.')),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='classstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2016)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='classteacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2016)),
                ('slug', models.SlugField(max_length=42)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classteacher_classSection', to='school_eduadmin.class_section')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('key', models.CharField(max_length=20)),
                ('total', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField(default=2016)),
                ('slug', models.SlugField(max_length=45)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_classadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('topics', models.TextField()),
                ('year', models.PositiveSmallIntegerField(default=2016)),
                ('slug', models.SlugField(max_length=65)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_eduadmin_classGroup_genadmin', to='school_genadmin.class_group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_eduadmin_subject_genadmin', to='school_genadmin.Subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_eduadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
    ]
