# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_genadmin', '0002_auto_20161206_1859'),
        ('school_teacher', '0001_initial'),
        ('school_student', '0001_initial'),
        ('school_user', '0002_remove_user_user_id'),
        ('school_eduadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classteacher_eduadmin_teacher_teacher', to='school_teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classteacher_eduadmin_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classstudent_classSection', to='school_eduadmin.class_section'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classstudent_eduadmin_student_student', to='school_student.Student'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classstudent_eduadmin_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AddField(
            model_name='class_section',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classSection_classadmin_teacher_teacher', to='school_teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='class_section',
            name='classgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classSection_classadmin_classGroup_genadmin', to='school_genadmin.class_group'),
        ),
        migrations.AddField(
            model_name='class_section',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classsection_classadmin_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together=set([('key', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set([('key', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='class_section',
            unique_together=set([('name', 'tenant')]),
        ),
    ]
