# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0002_auto_20161206_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_section',
            name='class_teacher',
        ),
        migrations.AlterField(
            model_name='exam',
            name='key',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2016),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='key',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together=set([('class_section', 'student', 'year', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together=set([('class_section', 'year', 'tenant')]),
        ),
    ]
