# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0003_auto_20161208_0854'),
        ('school_user', '0003_auto_20161208_0854'),
        ('school_teacher', '0001_initial'),
        ('school_eduadmin', '0003_auto_20161208_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Examiner_eduadmin_eduadmin_classSection', to='school_eduadmin.class_section')),
            ],
        ),
        migrations.CreateModel(
            name='subject_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, default=2016)),
                ('key', models.CharField(db_index=True, max_length=55)),
                ('slug', models.SlugField(max_length=80)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectTeacher_classSection', to='school_eduadmin.class_section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectTeacher_eduadmin_subject_genadmin', to='school_genadmin.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectTeacher_eduadmin_teacher_teacher', to='school_teacher.Teacher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectTeacher_eduadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='external_examiner',
            field=models.BooleanField(default=True, verbose_name='Will threre be external examiners to check student copies?'),
        ),
        migrations.AddField(
            model_name='examiner',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Examiner_exam', to='school_eduadmin.Exam'),
        ),
        migrations.AddField(
            model_name='examiner',
            name='external_teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExaminerExternal_eduadmin_teacher_teacher', to='school_teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='examiner',
            name='internal_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExaminerInternal_eduadmin_teacher_teacher', to='school_teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='examiner',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Examiner_eduadmin_genadmin_subject', to='school_genadmin.Subject'),
        ),
        migrations.AddField(
            model_name='examiner',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Examiner_eduadmin_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='subject_teacher',
            unique_together=set([('key', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='examiner',
            unique_together=set([('exam', 'class_section', 'subject', 'tenant')]),
        ),
    ]
