# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_teacher', '0001_initial'),
        ('school_eduadmin', '0004_auto_20161208_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examiner',
            old_name='internal_teacher',
            new_name='internal_examiner',
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='external_teacher',
        ),
        migrations.AddField(
            model_name='examiner',
            name='external_examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExaminerExternal_eduadmin_teacher_teacher', to='school_teacher.Teacher'),
        ),
    ]
