# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0003_auto_20161208_2258'),
        ('school_genadmin', '0004_auto_20161208_2258'),
        ('school_user', '0003_auto_20161208_0854'),
        ('school_eduadmin', '0005_auto_20161208_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2016)),
                ('slug', models.SlugField(max_length=65)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentHouse_eduadmin_genadmin_house', to='school_genadmin.House')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentHouse_eduadmin_student_student', to='school_student.Student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentHouse_eduadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterField(
            model_name='subject_teacher',
            name='key',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='subject_teacher',
            name='slug',
            field=models.SlugField(max_length=85),
        ),
        migrations.AlterUniqueTogether(
            name='student_house',
            unique_together=set([('house', 'student', 'year', 'tenant')]),
        ),
    ]
