# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0006_auto_20161208_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_section',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=15, verbose_name='Class Name with section'),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2016),
        ),
        migrations.AlterField(
            model_name='classteacher',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2016),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2016),
        ),
    ]
