# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-01 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0005_auto_20170101_1013'),
        ('school_teacher', '0005_auto_20161222_0620'),
        ('school_genadmin', '0007_auto_20161227_0744'),
        ('school_eduadmin', '0007_auto_20161221_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9)),
                ('period', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_classSection', to='school_eduadmin.class_section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_eduadmin_subject_genadmin', to='school_genadmin.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_eduadmin_teacher_teacher', to='school_teacher.Teacher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_eduadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='total_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_period', models.PositiveSmallIntegerField(db_index=True, verbose_name='Number of Periods in a day')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totalPeriod_eduadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2017),
        ),
        migrations.AlterField(
            model_name='classteacher',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2017),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2017),
        ),
        migrations.AlterField(
            model_name='student_house',
            name='year',
            field=models.PositiveSmallIntegerField(default=2017),
        ),
        migrations.AlterField(
            model_name='subject_teacher',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2017),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2017),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set([('day', 'period', 'year', 'tenant')]),
        ),
    ]
