# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-02 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0008_auto_20170101_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='slug',
            field=models.SlugField(default=8, max_length=42),
            preserve_default=False,
        ),
    ]
