# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0009_period_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudent',
            name='roll_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
