# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0010_classstudent_roll_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together=set([('class_section', 'roll_no', 'tenant'), ('class_section', 'student', 'year', 'tenant')]),
        ),
    ]
