# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-15 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0011_auto_20170105_0748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classstudent',
            unique_together=set([('class_section', 'roll_no', 'year', 'tenant'), ('class_section', 'student', 'year', 'tenant')]),
        ),
    ]
