# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-04 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0012_auto_20170115_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='day',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='subject_teacher',
            unique_together=set([('slug', 'tenant')]),
        ),
    ]
