# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0011_auto_20170213_0031'),
        ('school_eduadmin', '0015_auto_20170212_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('details', models.TextField()),
                ('show_from', models.DateField()),
                ('show_until', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticeBoard_eduadmin_user_tenant', to='school_user.Tenant')),
            ],
            options={
                'ordering': ('show_from', 'show_until'),
            },
        ),
    ]
