# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0016_notice_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='student_house',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='slug',
        ),
        migrations.AlterField(
            model_name='class_section',
            name='room',
            field=models.CharField(blank=True, max_length=10, verbose_name='Room name/no.'),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='roll_no',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='key',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject_teacher',
            unique_together=set([('class_section', 'subject', 'teacher', 'year', 'tenant')]),
        ),
    ]
