# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0017_auto_20170216_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_teacher',
            name='slug',
        ),
    ]
