# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0013_auto_20170218_0858'),
        ('school_eduadmin', '0018_remove_subject_teacher_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(verbose_name='Is this Term active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_eduadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='weightage',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Subject Weightage'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='key',
            field=models.CharField(max_length=20, verbose_name='Short Form'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='key',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_term', to='school_eduadmin.Term'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_term', to='school_eduadmin.Term'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set([('is_active', 'tenant')]),
        ),
    ]
