# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0019_auto_20170218_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('CCE', 'CCE'), ('Custom', 'Custom')], max_length=6)),
                ('opted', models.BooleanField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examCreation_eduadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='external_examiner',
        ),
        migrations.AddField(
            model_name='exam',
            name='weightage',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Exam Weightage'),
        ),
        migrations.AddField(
            model_name='term',
            name='weightage',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Term Weightage'),
        ),
        migrations.AlterField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is this Term active'),
        ),
        migrations.AlterUniqueTogether(
            name='exam_creation',
            unique_together=set([('exam_type', 'tenant')]),
        ),
    ]
