# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0020_auto_20170219_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set([('is_active', 'name', 'tenant')]),
        ),
    ]
