# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0026_auto_20170220_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2016),
            preserve_default=False,
        ),
    ]
