# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0027_auto_20170220_1718'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examiner',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='class_section',
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='external_examiner',
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='internal_examiner',
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='notice_board',
            name='tenant',
        ),
        migrations.AddField(
            model_name='exam',
            name='has_subexam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam_creation',
            name='is_term',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam_creation',
            name='year',
            field=models.PositiveSmallIntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='Is This Additional (Wont effect total calculation)?'),
        ),
        migrations.AlterField(
            model_name='exam_creation',
            name='exam_type',
            field=models.CharField(choices=[('CCE', 'CCE'), ('M', 'Marks Only'), ('MG', 'Marks And Grades')], max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='Examiner',
        ),
        migrations.DeleteModel(
            name='notice_board',
        ),
    ]
