# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0029_auto_20170227_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Subject Name')),
                ('grade_type', models.CharField(choices=[('S', 'Scholastic'), ('C', 'Co-scholastic')], max_length=1, verbose_name='Type of grade?')),
                ('min_mark', models.PositiveSmallIntegerField()),
                ('max_mark', models.PositiveSmallIntegerField()),
                ('grade', models.CharField(max_length=4)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradeTable_genadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='grade_table',
            unique_together=set([('grade_type', 'tenant')]),
        ),
    ]
