# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0031_remove_grade_table_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade_table',
            unique_together=set([]),
        ),
    ]
