# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0032_auto_20170301_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade_table',
            options={'ordering': ('tenant', 'sl_no')},
        ),
        migrations.AddField(
            model_name='grade_table',
            name='sl_no',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
