# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0033_auto_20170301_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudent',
            name='is_promoted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2017, verbose_name='Academic Year'),
        ),
    ]
