# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0034_auto_20170302_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstudent',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
