# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0036_auto_20170309_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ('class_group', 'id')},
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='is_elective',
            field=models.BooleanField(default=False, verbose_name='Is This An Elective?'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='Is This Additional (Wont effect total calculation in exam)?'),
        ),
    ]
