# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0037_auto_20170309_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='weightage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Exam Weightage'),
        ),
    ]
