# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0038_auto_20170310_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteacher',
            name='slug',
        ),
    ]
