# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0017_tenant_no_of_profile'),
        ('school_eduadmin', '0039_remove_classteacher_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam_creation',
            unique_together=set([('exam_type', 'year', 'tenant')]),
        ),
    ]
