# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0017_tenant_no_of_profile'),
        ('school_genadmin', '0029_auto_20170323_2054'),
        ('school_eduadmin', '0040_auto_20170320_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='syllabus_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabusTopic_syllabusSubject', to='school_genadmin.Subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabusTopic_eduadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='topics',
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together=set([('class_group', 'subject', 'year', 'tenant')]),
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='key',
        ),
    ]
