# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0030_auto_20170325_0908'),
        ('school_user', '0017_tenant_no_of_profile'),
        ('school_eduadmin', '0041_auto_20170323_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade_item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sl_no', models.PositiveSmallIntegerField()),
                ('min_mark', models.PositiveSmallIntegerField()),
                ('max_mark', models.PositiveSmallIntegerField()),
                ('grade', models.CharField(max_length=4)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('tenant', 'sl_no'),
            },
        ),
        migrations.AlterModelOptions(
            name='grade_table',
            options={},
        ),
        migrations.AddField(
            model_name='exam',
            name='classgroup',
            field=models.ManyToManyField(db_index=True, related_name='exam_eduadmin_classGroup_genadmin', to='school_genadmin.class_group'),
        ),
        migrations.AddField(
            model_name='grade_table',
            name='table_name',
            field=models.CharField(choices=[('S', 'Scholastic'), ('C', 'Co-scholastic')], default=1, max_length=20, verbose_name='Table Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='total',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Term Total'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='classgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classSection_eduadmin_classGroup_genadmin', to='school_genadmin.class_group'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classsection_eduadmin_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_eduadmin_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_term', to='school_eduadmin.Term'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade_table',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradeTable_eduadmin_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AlterField(
            model_name='term',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Term Number'),
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='Academic Year'),
        ),
        migrations.RemoveField(
            model_name='grade_table',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='grade_table',
            name='grade_point',
        ),
        migrations.RemoveField(
            model_name='grade_table',
            name='max_mark',
        ),
        migrations.RemoveField(
            model_name='grade_table',
            name='min_mark',
        ),
        migrations.RemoveField(
            model_name='grade_table',
            name='sl_no',
        ),
        migrations.AlterUniqueTogether(
            name='grade_table',
            unique_together=set([('table_name', 'tenant')]),
        ),
        migrations.AddField(
            model_name='grade_item',
            name='grade_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradeItem_gradeTable', to='school_eduadmin.grade_table'),
        ),
        migrations.AddField(
            model_name='grade_item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradeItem_eduadmin_user_tenant', to='school_user.Tenant'),
        ),
    ]
