# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0042_auto_20170327_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_creation',
            name='exam_type',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('M', 'Marks Only'), ('MG', 'Marks And Grades')], max_length=6),
        ),
        migrations.AlterField(
            model_name='syllabus_topic',
            name='month',
            field=models.TextField(),
        ),
    ]
