# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0044_auto_20170327_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade_table',
            name='table_name',
            field=models.CharField(choices=[('S', 'Scholastic'), ('C', 'Co-scholastic')], max_length=80, verbose_name='Table Name'),
        ),
    ]
