# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_eduadmin', '0045_auto_20170329_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='serial_no',
            field=models.PositiveSmallIntegerField(verbose_name='Exam number'),
        ),
    ]
