# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0017_tenant_no_of_profile'),
        ('school_eduadmin', '0046_auto_20170407_0003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set([('is_active', 'name', 'year', 'tenant')]),
        ),
    ]
