# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0017_tenant_no_of_profile'),
        ('school_eduadmin', '0047_auto_20170419_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set([('key', 'year', 'tenant')]),
        ),
    ]
