# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ispresent', models.CharField(db_index=True, max_length=12)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='exam_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ispresent', models.CharField(db_index=True, max_length=12)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
