# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_genadmin', '0002_auto_20161206_1859'),
        ('school_classadmin', '0002_auto_20161206_1859'),
        ('school_student', '0001_initial'),
        ('school_user', '0002_remove_user_user_id'),
        ('school_eduadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReport_classadmin_student_student', to='school_student.Student'),
        ),
        migrations.AddField(
            model_name='exam_report',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReport_classadmin_genadmin_subject', to='school_genadmin.Subject'),
        ),
        migrations.AddField(
            model_name='exam_report',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReport_classadmin_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_classadmin_eduadmin_classSection', to='school_eduadmin.class_section'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_classadmin_student_student', to='school_student.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_classadmin_user_tenant', to='school_user.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='exam_report',
            unique_together=set([('student', 'exam', 'subject', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('student', 'date')]),
        ),
    ]
