# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_classadmin', '0003_auto_20161206_1859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam_report',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='exam_report',
            name='class_section',
        ),
        migrations.RemoveField(
            model_name='exam_report',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='exam_report',
            name='student',
        ),
        migrations.RemoveField(
            model_name='exam_report',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='exam_report',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='exam_report',
        ),
    ]
