# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_genadmin', '0003_auto_20161208_0854'),
        ('school_user', '0003_auto_20161208_0854'),
        ('school_eduadmin', '0003_auto_20161208_0854'),
        ('school_student', '0001_initial'),
        ('school_classadmin', '0004_auto_20161208_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_score', models.PositiveSmallIntegerField()),
                ('internal_score', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField()),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReport_classadmin_eduadmin_classSection', to='school_eduadmin.class_section')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReport_classadmin_eduadmin_exam', to='school_eduadmin.Exam')),
                ('examInvigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReport_classadmin_eduadmin_examInvigilator', to='school_eduadmin.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReport_classadmin_student_student', to='school_student.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReport_classadmin_genadmin_subject', to='school_genadmin.Subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examReport_classadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exam_report',
            unique_together=set([('student', 'exam', 'subject')]),
        ),
    ]
