# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_user', '0004_auto_20161217_0924'),
        ('school_eduadmin', '0006_auto_20161208_2258'),
        ('school_genadmin', '0004_auto_20161208_2258'),
        ('school_classadmin', '0005_auto_20161208_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_details', models.TextField()),
                ('date', models.DateField()),
                ('key', models.CharField(db_index=True, max_length=12)),
                ('slug', models.SlugField()),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Homework_classadmin_eduadmin_classSection', to='school_eduadmin.class_section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Homework_classadmin_genadmin_subject', to='school_genadmin.Subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Homework_classadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('student', 'date', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='exam_report',
            unique_together=set([('student', 'exam', 'subject', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together=set([('key', 'tenant')]),
        ),
    ]
