# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_classadmin', '0007_auto_20161221_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_report',
            name='final_score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
