# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_classadmin', '0008_exam_report_final_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_report',
            name='remarks',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam_report',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examReport_classadmin_eduadmin_examiner', to='school_eduadmin.Examiner'),
        ),
        migrations.AlterField(
            model_name='exam_report',
            name='external_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
