# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_classadmin', '0009_auto_20161227_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_report',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
