# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_student', '0016_auto_20170209_1119'),
        ('school_user', '0013_auto_20170218_0858'),
        ('school_eduadmin', '0019_auto_20170218_0858'),
        ('school_classadmin', '0011_auto_20170216_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_coscholastic_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curricular_type', models.TextField(blank=True)),
                ('topic', models.TextField()),
                ('final_score', models.PositiveSmallIntegerField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=4)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examCoscholasticReport_classadmin_eduadmin_classSection', to='school_eduadmin.class_section')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examCoscholasticReport_classadmin_eduadmin_exam', to='school_eduadmin.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examCoscholasticReport_classadmin_student_student', to='school_student.Student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examCoscholasticReport_classadmin_user_tenant', to='school_user.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='exam_report',
            name='grade',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='exam_report',
            name='total',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='exam_report',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2016),
        ),
        migrations.AlterUniqueTogether(
            name='exam_coscholastic_report',
            unique_together=set([('student', 'exam', 'year', 'topic', 'tenant')]),
        ),
    ]
