# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_classadmin', '0015_auto_20170220_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_coscholastic_report',
            name='year',
        ),
    ]
