# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_classadmin', '0019_student_remark_student_remark_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='has_applied_leave',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
