# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_classadmin', '0020_auto_20170301_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_remark',
            name='remarked_by',
        ),
        migrations.RemoveField(
            model_name='student_remark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student_remark',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='student_remark_comment',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='student_remark_comment',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='student_remark',
        ),
        migrations.DeleteModel(
            name='student_remark_comment',
        ),
    ]
