# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_classadmin', '0021_auto_20170308_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_coscholastic_report',
            name='topic',
            field=models.TextField(),
        ),
    ]
