# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 03:20
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('remarks', models.TextField(blank=True)),
                ('account_type', models.CharField(choices=[('ca', 'Current Assets'), ('rec', 'Receivable/Sundry Debtors'), ('nca', 'Non Current/Long Term Assets'), ('cl', 'Current Liabilities'), ('pay', 'Payables/Sundry Creditors'), ('ncl', 'Non Current/Long Term Liabilities'), ('rev', 'Revenue'), ('indrev', 'Indirect Revenue'), ('direxp', 'Direct Expense'), ('indexp', 'Indirect Expense'), ('taxexp', 'Tax Expense'), ('equ', 'Equity/Owner/Capital')], max_length=30, verbose_name='Account type')),
                ('key', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='account_year',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('opening_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Opening Debit Balance')),
                ('opening_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Opening Credit Balance')),
                ('current_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountYear_account', to='distributor_account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='accounting_period',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start', models.DateField(db_index=True)),
                ('end', models.DateField(db_index=True)),
                ('current_period', models.BooleanField(verbose_name='Current Accounting Period?')),
                ('finalized', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountingPeriod_account_user_tenant', to='distributor_user.Tenant')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='inventory_value',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inventory_type', models.CharField(choices=[('O', 'Opening'), ('C', 'Closing')], max_length=1, verbose_name='Inventory type')),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryValue_accountingPeriod', to='distributor_account.accounting_period')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryValue_account_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('remarks', models.CharField(blank=True, max_length=80, null=True)),
                ('slug', models.SlugField()),
                ('key', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'ordering': ('date', 'group'),
            },
        ),
        migrations.CreateModel(
            name='journal_entry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=6, verbose_name='Transaction type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntry_account', to='distributor_account.Account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntry_journal', to='distributor_account.Journal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntry_account_user_tenant', to='distributor_user.Tenant')),
            ],
            options={
                'ordering': ('journal', '-transaction_type'),
            },
        ),
        migrations.CreateModel(
            name='journal_group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalGroup_account_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ledger_group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgergroup_account_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='payment_mode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Payment Mode Name')),
                ('default', models.BooleanField(default=False, verbose_name='Default Payment Mode ?')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentMode_account', to='distributor_account.Account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentMode_account_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_journalGroup', to='distributor_account.journal_group'),
        ),
        migrations.AddField(
            model_name='journal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_account_user_tenant', to='distributor_user.Tenant'),
        ),
        migrations.AddField(
            model_name='account_year',
            name='accounting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountYear_accountingPeriod', to='distributor_account.accounting_period'),
        ),
        migrations.AddField(
            model_name='account_year',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountYear_account_user_tenant', to='distributor_user.Tenant'),
        ),
        migrations.AddField(
            model_name='account',
            name='ledger_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_ledgerGroup', to='distributor_account.ledger_group'),
        ),
        migrations.AddField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_account_user_tenant', to='distributor_user.Tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='payment_mode',
            unique_together=set([('name', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='ledger_group',
            unique_together=set([('name', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='journal_group',
            unique_together=set([('name', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set([('key', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='inventory_value',
            unique_together=set([('inventory_type', 'accounting_period', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='accounting_period',
            unique_together=set([('start', 'end', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='account_year',
            unique_together=set([('account', 'accounting_period', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('name', 'tenant'), ('key', 'tenant')]),
        ),
    ]
