# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ca', 'Current Assets'), ('rec', 'Receivable/Sundry Debtors'), ('nca', 'Non Current/Long Term Assets'), ('cl', 'Current Liabilities'), ('pay', 'Payables/Sundry Creditors'), ('ncl', 'Non Current/Long Term Liabilities'), ('dirrev', 'Direct Revenue'), ('indrev', 'Indirect Revenue'), ('direxp', 'Direct Expense'), ('indexp', 'Indirect Expense'), ('taxexp', 'Tax Expense'), ('equ', 'Equity/Owner/Capital')], max_length=30, verbose_name='Account type'),
        ),
    ]
