# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0002_auto_20170517_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
        migrations.AlterField(
            model_name='journal_entry',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Debit'), (2, 'Credit')], verbose_name='Transaction type'),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='journal',
            name='key',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='slug',
        ),
    ]
