# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0006_journal_entry_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_transaction',
            name='transaction_bill_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal_entry',
            name='activity_type',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='tax_transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxTransaction_account_master_product', to='distributor_master.Product'),
        ),
        migrations.AlterField(
            model_name='tax_transaction',
            name='tax_percent',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
