# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0007_auto_20170531_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_year',
            name='first_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Credit Balance as on date of registration'),
        ),
        migrations.AddField(
            model_name='account_year',
            name='first_debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Debit Balance as on date of registration'),
        ),
        migrations.AddField(
            model_name='account_year',
            name='is_first_year',
            field=models.BooleanField(default=True),
        ),
    ]
