# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0008_auto_20170602_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting_period',
            name='is_first_year',
            field=models.BooleanField(default=False),
        ),
    ]
