# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0009_accounting_period_is_first_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
