# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0010_auto_20170607_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_contra',
            field=models.BooleanField(default=False),
        ),
    ]
