# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0012_auto_20170614_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax_transaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tax_transaction',
            name='product_name',
        ),
    ]
