# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0013_auto_20170614_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='transaction_bill_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
