# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0014_journal_transaction_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='trn_type',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
