# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0010_auto_20170701_1225'),
        ('distributor_account', '0015_journal_trn_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('key', models.CharField(db_index=True, max_length=15)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountInventory_account_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='account_year_inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('opening_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Opening Debit Balance')),
                ('opening_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Opening Credit Balance')),
                ('first_debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Debit Balance as on date of registration')),
                ('first_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Credit Balance as on date of registration')),
                ('current_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_first_year', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountYearInventory_accountInventory', to='distributor_account.Account')),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountYearInventory_accountingPeriod', to='distributor_account.accounting_period')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountYearInventory_account_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='account_year_inventory',
            unique_together=set([('account_inventory', 'accounting_period', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='account_inventory',
            unique_together=set([('name', 'tenant'), ('key', 'tenant')]),
        ),
    ]
