# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0016_auto_20170704_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_year_inventory',
            name='account_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountYearInventory_accountInventory', to='distributor_account.account_inventory'),
        ),
    ]
