# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0017_auto_20170704_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_transaction',
            name='is_registered',
            field=models.BooleanField(default=True),
        ),
    ]
