# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 01:37
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0010_auto_20170701_1225'),
        ('distributor_account', '0018_tax_transaction_is_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='journal_entry_inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Debit'), (2, 'Credit')], verbose_name='Transaction type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntryInventory_accountInventory', to='distributor_account.account_inventory')),
            ],
            options={
                'ordering': ('journal', '-transaction_type'),
            },
        ),
        migrations.CreateModel(
            name='journal_inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('transaction_bill_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('trn_type', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalInventory_account_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='journal_entry_inventory',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntryInventory_journalInventory', to='distributor_account.journal_inventory'),
        ),
        migrations.AddField(
            model_name='journal_entry_inventory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalEntryInventory_account_user_tenant', to='distributor_user.Tenant'),
        ),
    ]
