# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0012_auto_20170731_0947'),
        ('distributor_account', '0020_journal_other_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounting_group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountingGroup_account_user_tenant', to='distributor_user.Tenant')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='ledger_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_ledgerGroup', to='distributor_account.ledger_group'),
        ),
        migrations.AddField(
            model_name='account',
            name='accounting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_accountingGroup', to='distributor_account.accounting_group'),
        ),
        migrations.AlterUniqueTogether(
            name='accounting_group',
            unique_together=set([('name', 'tenant')]),
        ),
    ]
