# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0021_auto_20170811_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_transaction',
            name='bill_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tax_transaction',
            name='customer_gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
