# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0022_auto_20170901_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_transaction',
            name='line_wo_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
