# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0023_tax_transaction_line_wo_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_transaction',
            name='customer_state',
            field=models.CharField(blank=True, choices=[('35', 'Andaman & Nicobar Island'), ('37', 'Andhra Pradesh'), ('12', 'Arunachal Pradesh'), ('18', 'Assam'), ('10', 'Bihar'), ('04', 'Chandigarh'), ('22', 'Chattisgarh'), ('26', 'Dadra & Nagar Haveli'), ('25', 'Daman & Diu'), ('07', 'National Capital Territory of Delhi'), ('30', 'Goa'), ('24', 'Gujrat'), ('06', 'Haryana'), ('02', 'Himachal Pradesh'), ('01', 'Jammu & Kashmir'), ('20', 'Jharkhand'), ('29', 'Karnataka'), ('32', 'Kerala'), ('31', 'Lakshadweep'), ('23', 'Madhya Pradesh'), ('27', 'Maharashtra'), ('14', 'Manipur'), ('17', 'Meghalaya'), ('15', 'Mizoram'), ('13', 'Nagaland'), ('21', 'Odisha'), ('34', 'Puducherry'), ('03', 'Punjab'), ('08', 'Rajashtan'), ('11', 'Sikkim'), ('33', 'Tamil Nadu'), ('36', 'Telengana'), ('16', 'Tripura'), ('09', 'Uttar Pradesh'), ('05', 'Uttarkhand'), ('19', 'West Bengal')], max_length=4, null=True),
        ),
    ]
