# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0024_tax_transaction_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax_transaction',
            name='transaction_bill_no',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
