# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0025_auto_20170904_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_inventory',
            name='key',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='accounting_group',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
