# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 06:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0026_auto_20170915_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_entry',
            name='related_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
