# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0027_journal_entry_related_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory_value',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='inventory_value',
            name='accounting_period',
        ),
        migrations.RemoveField(
            model_name='inventory_value',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='inventory_value',
        ),
    ]
