# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0028_auto_20180131_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='remarks',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
