# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_account', '0029_auto_20180204_1826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounting_group',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accounting_group',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='account',
            name='accounting_group',
        ),
        migrations.DeleteModel(
            name='accounting_group',
        ),
    ]
