# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=12)),
                ('slug', models.SlugField(max_length=300)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grand_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesInvoice_sales_master_customer', to='distribution_master.Customer')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='salesLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=20)),
                ('sub_key', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('discount1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('free', models.PositiveSmallIntegerField(default=0)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_type', models.CharField(max_length=50)),
                ('vat_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('item_key', models.CharField(max_length=10, verbose_name='product-id')),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesLineItem_sales_sales_salesInvoice', to='distribution_sales.salesInvoice')),
            ],
        ),
    ]
