# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution_sales', '0001_initial'),
        ('distribution_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_sales_user_tenant', to='distribution_user.Tenant'),
        ),
    ]
