# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_sales', '0002_salesinvoice_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collected_on', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='salespayment',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesPayment_sales_sales_salesInvoice', to='distribution_sales.salesInvoice'),
        ),
    ]
