# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_sales', '0003_auto_20160904_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespayment',
            name='collected_on',
            field=models.DateTimeField(null=True),
        ),
    ]
