# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0014_subproduct_tenant'),
        ('distribution_sales', '0004_auto_20160904_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='salesInvoice_sales_master_warehouse', to='distribution_master.Warehouse'),
            preserve_default=False,
        ),
    ]
