# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0014_subproduct_tenant'),
        ('distribution_sales', '0005_salesinvoice_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespayment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salespayment_sales_master_customer', to='distribution_master.Customer'),
            preserve_default=False,
        ),
    ]
