# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_sales', '0006_salespayment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespayment',
            name='customer',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
