# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0015_auto_20161014_1119'),
        ('distribution_user', '0001_initial'),
        ('distribution_sales', '0007_auto_20161002_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(blank=True, max_length=12)),
                ('note_type', models.CharField(choices=[('Goods Return', 'Goods Return'), ('Payment Adjustment', 'Payment Adjustment')], max_length=12)),
                ('slug', models.SlugField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditNote_sales_master_customer', to='distribution_master.Customer')),
                ('invoice_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditNote_salesInvoice', to='distribution_sales.salesInvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditNote_sales_user_tenant', to='distribution_user.Tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditNote_sales_master_warehouse', to='distribution_master.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='creditNoteLineDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('creditnote_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditNoteLineDetails_creditNote', to='distribution_sales.creditNote')),
            ],
        ),
        migrations.CreateModel(
            name='creditNoteLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=20)),
                ('sub_key', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('creditnote_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditNoteLineItem_creditNote', to='distribution_sales.creditNote')),
            ],
        ),
    ]
