# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_accounts', '0017_auto_20161023_1005'),
        ('distribution_sales', '0008_creditnote_creditnotelinedetails_creditnotelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespayment',
            name='cheque_rtgs_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salespayment',
            name='payment_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salesPayment_sales_accounts_paymentMode', to='distribution_accounts.paymentMode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesPayment_salesInvoice', to='distribution_sales.salesInvoice'),
        ),
    ]
