# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_sales', '0010_creditnotelineitem_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotelineitem',
            name='vat_type',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleslineitem',
            name='vat_type',
            field=models.CharField(max_length=30),
        ),
    ]
