# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor_user', '0001_initial'),
        ('distributor_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purchase_quantity', models.PositiveSmallIntegerField(db_index=True)),
                ('quantity_available', models.PositiveSmallIntegerField(db_index=True)),
                ('purchase_date', models.DateField(blank=True, db_index=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tentative_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MRP')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_inventory_master_product', to='distributor_master.Product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_inventory_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_inventory_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='inventory_ledger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Purchase'), (2, 'Sales Return'), (3, 'Other Inward'), (4, 'Sales'), (5, 'Purchase Return'), (6, 'Other Outward')], db_index=True, verbose_name='Transaction type')),
                ('date', models.DateField(db_index=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_bill_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryLedger_inventory_master_product', to='distributor_master.Product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryLedger_inventory_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryLedger_inventory_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='inventory_reserve',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_reserve', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('inventory_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MRP')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryReserve_inventory_master_product', to='distributor_master.Product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryReserve_inventory_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryReserve_inventory_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='inventory_warehouse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity_in_hand', models.PositiveSmallIntegerField(db_index=True)),
                ('quantity_po', models.PositiveSmallIntegerField(default=0)),
                ('quantity_reserve', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryWarehouse_inventory_master_product', to='distributor_master.Product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryWarehouse_inventory_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryWarehouse_inventory_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='warehouse_valuation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valuation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseValuation_inventory_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouseValuation_inventory_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
    ]
