# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0005_auto_20170529_2014'),
        ('distributor_user', '0002_auto_20170517_1647'),
        ('distributor_inventory', '0002_auto_20170520_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='initial_inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(db_index=True)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tentative_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MRP')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initialInventory_inventory_master_product', to='distributor_master.Product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initialInventory_inventory_user_tenant', to='distributor_user.Tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initialInventory_inventory_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
    ]
