# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_user', '0004_user_permission'),
        ('distributor_master', '0006_auto_20170607_0926'),
        ('distributor_inventory', '0003_initial_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_transfer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transfer_id', models.PositiveIntegerField(db_index=True)),
                ('initiated_on', models.DateField(blank=True, db_index=True, null=True)),
                ('received_on', models.DateField(blank=True, db_index=True, null=True)),
                ('in_transit', models.BooleanField(db_index=True, default=True)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryTransferFrom_inventory_master_warehouse', to='distributor_master.Warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryTransfer_inventory_user_tenant', to='distributor_user.Tenant')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryTransferTo_inventory_master_warehouse', to='distributor_master.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='inventory_transfer_items',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inventory_id', models.BigIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tentative_sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MRP')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryTransferItem_inventory_master_product', to='distributor_master.Product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryTransferItem_inventory_user_tenant', to='distributor_user.Tenant')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryTransferItems_inventoryTransfer', to='distributor_inventory.inventory_transfer')),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tentative_sales_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
