# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_master', '0007_auto_20170608_1118'),
        ('distributor_inventory', '0004_auto_20170608_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_transfer',
            name='total_value',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer_items',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryTransferItem_inventory_master_unit', to='distributor_master.Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory_ledger',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Purchase'), (2, 'Sales'), (3, 'Sales Return'), (4, 'Other Inward'), (5, 'Purchase Return'), (6, 'Other Outward'), (7, 'Transfer Outward'), (8, 'Transfer Inward')], db_index=True, verbose_name='Transaction type'),
        ),
    ]
