# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_inventory', '0005_auto_20170609_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_warehouse',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory_warehouse',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='inventory_warehouse',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='initial_inventory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory_ledger',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory_reserve',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer_items',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse_valuation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='inventory_warehouse',
        ),
    ]
