# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor_inventory', '0011_auto_20170710_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_transfer',
            name='from_warehouse_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer',
            name='from_warehouse_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer',
            name='from_warehouse_pin',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer',
            name='from_warehouse_state',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer',
            name='to_warehouse_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer',
            name='to_warehouse_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer',
            name='to_warehouse_pin',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer',
            name='to_warehouse_state',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer_items',
            name='product_hsn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventory_transfer_items',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_transfer',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryTransferFrom_inventory_master_warehouse', to='distributor_master.Warehouse'),
        ),
        migrations.AlterField(
            model_name='inventory_transfer',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryTransferTo_inventory_master_warehouse', to='distributor_master.Warehouse'),
        ),
        migrations.AlterField(
            model_name='inventory_transfer_items',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryTransferItem_inventory_master_product', to='distributor_master.Product'),
        ),
    ]
