# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=20)),
                ('key', models.CharField(max_length=20)),
                ('address', models.TextField(unique=True)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('cst_no', models.CharField(blank=True, max_length=20)),
                ('vat_no', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=32)),
                ('key', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail id')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=20)),
                ('key', models.CharField(max_length=20, verbose_name='product-id')),
                ('vat_type', models.CharField(choices=[('On MRP', 'On MRP'), ('On Cost Price', 'On Cost Price'), ('No VAT', 'No VAT')], default='on cost_price', max_length=15, verbose_name='VAT type')),
                ('vat_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='subProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_key', models.CharField(max_length=20)),
                ('batch', models.CharField(blank=True, max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MRP')),
                ('discount1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('discount2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scheme', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=10)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=20)),
                ('key', models.CharField(max_length=20)),
                ('address', models.TextField(unique=True)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=20)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
