# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution_master', '0001_initial'),
        ('distribution_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_master_user_tenant', to='distribution_user.Tenant'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_master_user_tenant', to='distribution_user.Tenant'),
        ),
        migrations.AddField(
            model_name='unit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_master_user_tenant', to='distribution_user.Tenant'),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subProduct_master_master_product', to='distribution_master.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_master_master_manufacturer', to='distribution_master.Manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_master_user_tenant', to='distribution_user.Tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_master_master_unit', to='distribution_master.Unit'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_master_user_tenant', to='distribution_user.Tenant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_master_user_tenant', to='distribution_user.Tenant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_master_master_zone', to='distribution_master.Zone'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together=set([('key', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set([('name', 'tenant'), ('symbol', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='subproduct',
            unique_together=set([('sub_key', 'product')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('key', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='manufacturer',
            unique_together=set([('key', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('key', 'tenant')]),
        ),
    ]
