# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0002_auto_20160904_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
    ]
