# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0004_auto_20160904_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('zone', 'name')},
        ),
    ]
