# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0006_auto_20160915_0308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountchart',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountchart',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accountingperiod',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='accountChart',
        ),
        migrations.DeleteModel(
            name='accountingPeriod',
        ),
    ]
