# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-29 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0007_auto_20160915_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='unit',
            name='slug',
            field=models.SlugField(max_length=22),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='zone',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
    ]
