# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_user', '0001_initial'),
        ('distribution_master', '0008_auto_20160929_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('slug', models.SlugField(max_length=22)),
                ('remarks', models.TextField(blank=True)),
                ('default', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Default Warehouse ?')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_master_user_tenant', to='distribution_user.Tenant')),
            ],
            options={
                'ordering': ('-default', 'address'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set([('key', 'address', 'tenant')]),
        ),
    ]
