# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0009_auto_20160930_0914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together=set([('key', 'tenant')]),
        ),
    ]
