# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0010_auto_20161001_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
