# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0011_auto_20161001_0308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set([('key', 'tenant')]),
        ),
    ]
