# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_user', '0001_initial'),
        ('distribution_master', '0013_auto_20161001_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='subproduct_master_user_tenant', to='distribution_user.Tenant'),
            preserve_default=False,
        ),
    ]
