# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_user', '0001_initial'),
        ('distribution_master', '0014_subproduct_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=22)),
                ('details', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_master_user_tenant', to='distribution_user.Tenant')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='subproduct',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_master_master_unit', to='distribution_master.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='dimension',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='unit_dimension', to='distribution_master.Dimension'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together=set([('name', 'tenant')]),
        ),
    ]
