# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0015_auto_20161014_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='details',
        ),
        migrations.AddField(
            model_name='unit',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
