# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0016_auto_20161023_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_type',
            field=models.CharField(choices=[('No VAT', 'No VAT'), ('On MRP', 'On MRP'), ('On Cost Price', 'On Cost Price')], default='on cost_price', max_length=15, verbose_name='VAT type'),
        ),
    ]
