# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0013_auto_20161001_0720'),
        ('distribution_inventory', '0002_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_inventory_master_warehouse', to='distribution_master.Warehouse'),
            preserve_default=False,
        ),
    ]
