# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_inventory', '0003_inventory_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('warehouse', 'item')},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_inventory_master_warehouse', to='distribution_master.Warehouse'),
        ),
    ]
