# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_inventory', '0004_auto_20161001_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_inventory_master_subproduct', to='distribution_master.subProduct'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([('item', 'warehouse')]),
        ),
    ]
