# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_master', '0015_auto_20161014_1119'),
        ('distribution_inventory', '0005_auto_20161001_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='damagedInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damagedinventory_inventory_master_subproduct', to='distribution_master.subProduct')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damagedinventory_inventory_master_warehouse', to='distribution_master.Warehouse')),
            ],
            options={
                'ordering': ('warehouse', 'item'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='damagedinventory',
            unique_together=set([('item', 'warehouse')]),
        ),
    ]
