# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_user', '0001_initial'),
        ('distribution_master', '0015_auto_20161014_1119'),
        ('distribution_inventory', '0006_auto_20161018_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnableInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnableinventory_inventory_master_subproduct', to='distribution_master.subProduct')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnableinventory_inventory_master_user_tenant', to='distribution_user.Tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnableinventory_inventory_master_warehouse', to='distribution_master.Warehouse')),
            ],
            options={
                'ordering': ('warehouse', 'item'),
            },
        ),
        migrations.AddField(
            model_name='damagedinventory',
            name='tenant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='damagedinventory_inventory_master_user_tenant', to='distribution_user.Tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='tenant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_inventory_master_user_tenant', to='distribution_user.Tenant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='returnableinventory',
            unique_together=set([('item', 'warehouse')]),
        ),
    ]
